### ISSUE TITLE
bug：resource形式加载的apng无法在release包下展示

### ISSUE THREAD

**Issue by Youdau** [penfeizhou/APNG4Android#100]
使用res形式进行加载的apng图在release包下无法加载（只会显示第一帧），debug包可以加载
asset形式进行加载的话都可以

**Comment by penfeizhou** [comment]
Android在编译时aapt会对drawable的资源进行压缩,这种压缩会破坏apng的文件结构.所以apng格式的文件请不要放到drawable里.
