### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 6623696 free bytes and 6MB until OOM

### ISSUE THREAD

**Issue by Beseting** [penfeizhou/APNG4Android#103]
场景如下：
动态addView（ImageView） Glide加载APNGDrawable 完成一组动画后removeView（ImageView）且imageView.setImageDrawable(null);imageView = null;
多次循环几组这样的组动画后抛出内存溢出异常
请问是否存在需要手动回收的API呢？

E/AndroidRuntime: FATAL EXCEPTION: FrameDecoderExecutor-0
    Process: cn.wemew.desktopscreen, PID: 7896
    java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 6623696 free bytes and 6MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:893)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:870)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:837)
        at com.github.penfeizhou.animation.FrameAnimationDrawable.onRender(FrameAnimationDrawable.java:204)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:64)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:310)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
        at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(FrameSeqDecoder.java:280)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by penfeizhou** [comment]
使用Glide加载的话会自动回收内存,
您这种情况请帮忙提供使用处的代码看一下.

**Comment by Beseting** [comment]
//Glide加载APNG
Glide.with(App.getAppContext()).load(apngDrawable).into(iv);

**Comment by Beseting** [comment]
这里是这样的场景，你那边可以复现一下；
Activity根布局RelativeLayout来addView(ImageView)，ImageView是代码动态创建的，利用Glide来加载APNGDrawable在这个ImageView上，在ImageView的动画播放完成后，removeView(iv)；移除掉这个ImageView，同时设置imageView.setImageDrawable(null);imageView = null;apngDrawable.stop();

大概循环几次动态创建ImageView和removeView后，就抛OOM了

不清楚框架是否需要注意或调用回收机制？

**Comment by penfeizhou** [comment]
请试着直接使用
```java
imageView.setImageDrawable(animationDrawable)
```
看是否有同样的问题.

使用Glide.with(xxx).load(apngDrawable)时apngDrawable会作为内存缓存被缓存下来,
您也可以选择不使用内存缓存来避免这个问题.

**Comment by Beseting** [comment]
imageView.setImageDrawable(animationDrawable);试过了
而且在removeView的同时，也做了Glide.with(iv).clear(view);

依然要OOM

**Comment by penfeizhou** [comment]
不使用Glide也会有问题吗?

**Comment by Beseting** [comment]
对的，测试过了！

**Comment by penfeizhou** [comment]
按你的描述,测试代码如下
```java
public class APNGTestActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_apnglib);
        LinearLayout linearLayout = findViewById(R.id.layout);
        work(linearLayout);
    }

    private void work(final LinearLayout linearLayout) {
        linearLayout.removeAllViews();
        final ImageView imageView = new ImageView(this);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        layoutParams.bottomMargin = 50;
        layoutParams.topMargin = 50;
        linearLayout.addView(imageView, layoutParams);
        final APNGDrawable apngDrawable = APNGDrawable.fromAsset(this, "world-cup.png");
        apngDrawable.setLoopLimit(1);
        imageView.setImageDrawable(apngDrawable);
        apngDrawable.registerAnimationCallback(new Animatable2Compat.AnimationCallback() {
            @Override
            public void onAnimationEnd(Drawable drawable) {
                super.onAnimationEnd(drawable);
                apngDrawable.unregisterAnimationCallback(this);
                imageView.setImageDrawable(null);
                apngDrawable.stop();
                work(linearLayout);
            }
        });
    }
}
```
![image](https://user-images.githubusercontent.com/9526211/120980525-4969c100-c7a9-11eb-8d4e-a87531a44eb3.png)
从Profiler中可以看出内存没有泄漏的地方,
您可以直接通过Android Studio的Profiler dump内存看一下泄漏的地点在哪里.

**Comment by Beseting** [comment]
循环次数够多，单次加载apngDrawable1~3个，在几分钟后必出现OOM，单个apng资源图约几兆

**Comment by penfeizhou** [comment]
麻烦提供一个可以复现的Demo代码,按这上面的代码,是无法复现的.这是无限循环.

**Comment by penfeizhou** [comment]
![image](https://user-images.githubusercontent.com/9526211/120984708-7b7d2200-c7ad-11eb-8ac0-2bf108d0aeac.png)
换了一个28M的PNG图片,内存依然是周期性增长和释放.

**Comment by Beseting** [comment]
稍等，我做个demo呢，这边复现的场景不是一张图哦  就是多个png组合为一个场景 多个场景顺序连接就是一组完整的动画  连续这样的完整动画  几次后就OOM了

**Comment by Beseting** [comment]
demo已上传
https://gitee.com/jabez/apngdemo
oom已重现  大概循环到6次以上就OOM了

**Comment by penfeizhou** [comment]
![image](https://user-images.githubusercontent.com/9526211/120997440-c735c880-c7b9-11eb-86c5-c36d09cda2cc.png)
用Pixel 3未出现OOM,但从Profier内存看确实存在内存泄露.

**Comment by Beseting** [comment]
对 持续在增长

**Comment by penfeizhou** [comment]
从图中看主要的增长是native memory,这部分主要是bitmap创建的开销,从你的demo中看,每次的循环播放都是新建apngdrawable的实例,这需要立即分配出大量的Native Memory,小内存手机释放不及时就会导致OOM.
建议不要在每次执行过程新建drawable实例,这确实会给Native Memory造成压力.

**Comment by Beseting** [comment]
找到原因了，释放资源的时候需要apngDrawable.stop(); apngDrawable=null，且iv.setImageDrawable(null); iv = null;

虽然循环中是新建APNGDrawable实例，但在使用完成后合理回收即可！
