### ISSUE TITLE
app切换黑暗模式的时候，重新打开当前界面，动画会定住

### ISSUE THREAD

**Issue by liuhuan8986** [penfeizhou/APNG4Android#110]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | e.g. Huawei 荣耀V20                               |      |
| System Version               | e.g.  10.0                                             |      |
| APNG4Android Library Version | e.g.  2.10.0                                           |      |
| Repro rate                   | e.g. all the time 100%   |      |
| Repro with our demo project  | e.g 不会           |      |
| Demo project link            | e.g.   |      |

### Issue Description and Steps

1.app使用Glide插件，加载网络上的Apng和Gif格式的图片
2.app切换黑暗模式的时候，会重新打开当前界面，此时，界面上的Apng和Gif图片的动画会定住在某一帧，没有动画效果
3.此时若熄屏开屏则动画会重新执行

**Comment by jingpeng** [comment]
不使用Glide加载，转而使用APNGDrawble.fromXXX提供的API进行start和stop控制

**Comment by liuhuan8986** [comment]
不使用Glide 加载的话，我整个项目都要APNGDrawble.fromXXX，工作量太大了
