### ISSUE TITLE
播放到一半退到后台，回来会重新播放一次

### ISSUE THREAD

**Issue by li-xiaojun** [penfeizhou/APNG4Android#115]
如题，
应该是重新回来引发了 下列调用：
```
FrameAnimationDrawable.setBound() -> frameSeqDecoder.setDesiredSize -> innerStart()
```
在innerStart()内部加个isRunning()判断应该可以，
期待修复！

**Comment by jingpeng** [comment]
你是使用glide加载么

**Comment by penfeizhou** [comment]
> 如题， 应该是重新回来引发了 下列调用：
> 
> ```
> FrameAnimationDrawable.setBound() -> frameSeqDecoder.setDesiredSize -> innerStart()
> ```
> 
> 在innerStart()内部加个isRunning()判断应该可以， 期待修复！

目前的机制是退到后台后会自动调用stop方法,释放掉资源,等到前台后重新start播放.
如果不需要自动管理,可以调用`webpDrawable.setAutoPlay(false)`,不过这样的话需要你手动开始`start`.

**Comment by jingpeng** [comment]
WebPDrawable drawable = WebPDrawable.fromAsset(this, assetFile);
((WebPDrawable) drawable).setAutoPlay(false);
((WebPDrawable) drawable).setLoopLimit(1);
((WebPDrawable) drawable).start();

你可以试下这样写

**Comment by jingpeng** [comment]
> WebPDrawable drawable = WebPDrawable.fromAsset(this, assetFile); ((WebPDrawable) drawable).setAutoPlay(false); ((WebPDrawable) drawable).setLoopLimit(1); ((WebPDrawable) drawable).start();
> 
> 你可以试下这样写

我这里这样写是没问题的，切换后台回来也不会重播

**Comment by jingpeng** [comment]
drawable = WebPDrawable.fromAsset(this, assetFile);
                ((WebPDrawable)drawable).setLoopLimit(1);
                ((WebPDrawable)drawable).setAutoPlay(false);
                ((WebPDrawable)drawable).registerAnimationCallback(new Animatable2Compat.AnimationCallback() {
                    @Override
                    public void onAnimationEnd(Drawable drawable) {
                        super.onAnimationEnd(drawable);
                    }

                    @Override
                    public void onAnimationStart(Drawable drawable) {
                        super.onAnimationStart(drawable);
                    }
                });
                ((WebPDrawable) drawable).start();

和你源码一致我这里后台回到前台不会，你ImageView前后台切换或者onEnd有做什么其他事情么

**Comment by jingpeng** [comment]
@li-xiaojun 或者你给我下你的demo工程

**Comment by li-xiaojun** [comment]
@jingpeng sorry，我的代码问题。
