### ISSUE TITLE
[BUG] some images are not loaded (using glide plugin)

### ISSUE THREAD

**Issue by adbenitez** [penfeizhou/APNG4Android#119]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | Samsung A10                               |      |
| System Version               | e.g.  10.0                                             |      |
| APNG4Android Library Version | e.g.  2.14.0                                           |      |
| Repro rate                   | all the time (100%)   |      |
| Repro with our demo project  | the demo doesn't seems to work well in general, the glide section shows nothing, (watching the logcat, issues with SSL loading some images remotely it seems, would also be nice if you add an option to attach images so people can test with certain images            |      |
| Demo project link            | this is happening to https://github.com/deltachat/deltachat-android app, if you try to attach the images I attach in this issue, with most images it doesn't happens, it seems related to image resolution somehow: https://github.com/deltachat/deltachat-android/issues/1915 |      |

### Issue Description and Steps

when I try to show this image:
![2021-07-20-02-38](https://user-images.githubusercontent.com/24558636/137603116-9b27f0b2-741b-4510-b662-0ed45b2b21b1.gif)

I get this error:
```
10-16 18:00:25.150 26761 30234 W System.err: java.lang.IllegalArgumentException: Bad position 786474/786432
10-16 18:00:25.152 26761 30234 W System.err:    at java.nio.Buffer.position(Buffer.java:259)
10-16 18:00:25.154 26761 30234 W System.err:    at java.nio.ByteBuffer.position(ByteBuffer.java:812)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.io.ByteBufferReader.skip(ByteBufferReader.java:24)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.io.FilterReader.skip(FilterReader.java:20)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.gif.decode.ImageDescriptor.receive(ImageDescriptor.java:145)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.gif.decode.GifParser.parse(GifParser.java:118)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.gif.decode.GifDecoder.read(GifDecoder.java:73)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.gif.decode.GifDecoder.read(GifDecoder.java:26)
10-16 18:00:25.155 26761 30234 W System.err:    at com.github.penfeizhou.animation.decode.FrameSeqDecoder$5.run(FrameSeqDecoder.java:226)
10-16 18:00:25.155 26761 30234 W System.err:    at android.os.Handler.handleCallback(Handler.java:883)
10-16 18:00:25.155 26761 30234 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:100)
10-16 18:00:25.155 26761 30234 W System.err:    at android.os.Looper.loop(Looper.java:237)
10-16 18:00:25.155 26761 30234 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)
```

This image is also not loaded (99% of the time), but I don't see any errors in logcat:
![2021-05-04-00-09](https://user-images.githubusercontent.com/24558636/137603131-443838ca-7f44-4650-8334-f7077e684950.png)

**Comment by penfeizhou** [comment]
This gif image's format has some problem at the end.
In chrome, this gif play once. in safari, this can play normaly.
I guess it is because of some compat operation.
I'll do the same at my library, compating this situation.
Thank you for the feedback.

**Comment by adbenitez** [comment]
hi @penfeizhou, good news, I just tried 2.25.0, and now images like the one attached at the end of the issue description are rendered properly, thanks a lot! keep the good work!!!
