### ISSUE TITLE
libanimation-decoder-gif.so导致crash

### ISSUE THREAD

**Issue by Lieeber** [penfeizhou/APNG4Android#123]
![image](https://user-images.githubusercontent.com/8670932/140702662-524abfa5-abdc-4946-9978-4c752f748fc3.png)
跟踪起来太困难了，大致报错好像是由于GifDecoder.cpp中的memcpy这一行代码
![image](https://user-images.githubusercontent.com/8670932/140702785-a7ae9b56-e29d-4d06-a30b-106ca127fdcd.png)

**Comment by penfeizhou** [comment]
请问这个Crash出现的条件是什么?特定机型还是特定文件?

**Comment by Lieeber** [comment]
https://cdn.pokekara.com/sp1/pokekara/gif/small/4e/21/4e454f9208a5344fd3e1ab951abc8d21_434-434-1.gif
这张图用glide插件加载后崩溃 ，你可以试一下。

**Comment by penfeizhou** [comment]
感谢反馈该问题
v2.16.0已发布,修复此问题.

**Comment by Lieeber** [comment]
谢谢 那我用新版试试。

**Comment by penfeizhou** [comment]
该issue先关闭,有问题请继续反馈
