### ISSUE TITLE
use glide load apngDrawable can't callback(onAnimationEnd) properly

### ISSUE THREAD

**Issue by Beseting** [penfeizhou/APNG4Android#126]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | e.g. Emulator&Android Pad                               |      |
| System Version               | e.g.  8.0                                             |      |
| APNG4Android Library Version | e.g.  2.16.0                                           |      |
| Repro rate                   | e.g. all the time (100%)    |      |
| Repro with our demo project  | e.g. 100%happen            |      |
| Demo project link            | e.g. see description |      |

### Issue Description and Steps

When I use Glide load apngDrawable,the AnimationCallback doesn't work,It's get back first.
And Then,when I use imageView.setImageDrawable(apngDrawableExpression),it works!
Demo code:
val apngDrawable = APNGDrawable(FileLoader(filePath))
apngDrawable.setLoopLimit(3)
apngDrawable.registerAnimationCallback(object: Animatable2Compat.AnimationCallback(){
                    override fun onAnimationEnd(drawable: Drawable?) {
                        super.onAnimationEnd(drawable)
                        ToastUtils.showShort("end")
                    }
                })
apngDrawable.setAutoPlay(true)
// use glide,callback doesn't work properly
Glide.with(imageView).load(apngDrawable).into(imageView)
// use imageView.setImageDrawable(),callback works
imageView.setImageDrawable(apngDrawableExpression)

**Comment by jingpeng** [comment]
I'll check the logic

**Comment by jingpeng** [comment]
when you use glide to load apng drawable, please setAutoPlay(false) for accurate callback

**Comment by Beseting** [comment]
> when you use glide to load apng drawable, please setAutoPlay(false) for accurate callback

Thanks for your reply，I follow your code,the callback accurate worked,thank you very much!

**Comment by jingpeng** [comment]
you are welcome!
