### ISSUE TITLE
fitCenter() APNG

### ISSUE THREAD

**Issue by sarzhan** [penfeizhou/APNG4Android#128]
Hello.
I am using your plugin 'com.github.penfeizhou.android.animation: glide-plugin: 2.12.0' to display APNG files. I am using .fitCenter () which is a cropping technique that scales the image (GIF and APNG set it without changing the scale).

GlideApp.with (this)
             .load (data.filePath)
             .fitCenter ()
             .into (preview)

Can you suggest what could be the reason?

**Comment by penfeizhou** [comment]
This library does not support Glide's transform operation.

**Comment by sarzhan** [comment]
Thank you
