### ISSUE TITLE
华为手机适配问题，apng会一闪一闪的

### ISSUE THREAD

**Issue by LuoGuoXin** [penfeizhou/APNG4Android#131]
华为p20，apng会一闪一闪的，其他手机不会。[https://yd.awaterbear.com/image/yqw/fb7a967ea6950c-550x550.png](url)

**Comment by penfeizhou** [comment]
请提供具体的API使用方式或者可复现的demo工程

**Comment by LuoGuoXin** [comment]
fun ImageView.setApng(
    context: Context,
    fileName: String,
    loop: Int = 0,
    callback: () -> Unit
) {
    if (TextUtils.isEmpty(fileName)) {
        return
    }
    val names = fileName.split("/")
    if (names.size < 2) {
        return
    }
    val fileName = names[names.size - 1]
    val filePath = context.filesDir.absolutePath + "/" + fileName
    val file = File(filePath)
    if (!file.exists()) {
        return
    }
    val assetLoader = FileLoader(filePath)
    val apngDrawable = APNGDrawable(assetLoader)
    if (loop != 0) {
        apngDrawable.setLoopLimit(loop)
    }
    apngDrawable.registerAnimationCallback(object : Animatable2Compat.AnimationCallback() {
        override fun onAnimationEnd(drawable: Drawable?) {
            super.onAnimationEnd(drawable)
            callback.invoke()
        }
    })
    this.setImageDrawable(apngDrawable)
}

我是把图片下载到本地后，加载的。

**Comment by jingpeng** [comment]
我测了下，貌似P20这里未出现一闪一闪的效果

https://user-images.githubusercontent.com/5223226/146511420-88e8dd94-111c-42d2-8dae-ef896cd5b209.mp4

**Comment by jingpeng** [comment]
所以请确认下你的callback函数以及ImageView还做了哪些别的事情

**Comment by LuoGuoXin** [comment]
https://yd.awaterbear.com/image/yqw/4c84c8c027e05d-550x550.png
试试这个，刚刚那个我这边也是正常的

**Comment by LuoGuoXin** [comment]
就p20会，安卓9，其他手机，小米的啥的不会

**Comment by jingpeng** [comment]
![Screenshot_20211217_164605_com android settings](https://user-images.githubusercontent.com/5223226/146515984-47be5aaa-07ee-41c9-abf8-286528f6e7a4.jpg)

**Comment by jingpeng** [comment]
> 就p20会，安卓9，其他手机，小米的啥的不会

要么你可以看下P20的其他版本的ROM？我这里是Android 10 EMUI 10

**Comment by penfeizhou** [comment]
@LuoGuoXin 建议创建个简单的demo工程 ,看是否有问题 [APNGTestActivity.java](https://github.com/penfeizhou/APNG4Android/blob/master/app/src/main/java/com/github/penfeizhou/animation/demo/APNGTestActivity.java)
