### ISSUE TITLE
Webp Animated load from web use Glide doesn't animated

### ISSUE THREAD

**Issue by shily** [penfeizhou/APNG4Android#132]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | Galaxy A51 5G                               |      |
| System Version               | Android 11                                             |      |
| APNG4Android Library Version | 2.17.0                                          |      |
| Repro rate                   | all the time (100%)    |      |
| Repro with our demo project  | use case not present in demo project            |      |
| Demo project link            | https://github.com/shily/APNG4Android-WEBP-BUG |      |

### Issue Description and Steps
Glide loaded image from  URL doesn't animate expected

```
implementation 'com.github.bumptech.glide:glide:4.12.0'
implementation 'com.github.bumptech.glide:annotations:4.12.0'
annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.17.0'
```

**Comment by jingpeng** [comment]
你需要实现一个GlideModule
```
package com.github.webpanimated;

import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public class MyGlideModule extends AppGlideModule {
}
```

**Comment by jingpeng** [comment]
> 你需要实现一个GlideModule
> 
> ```
> package com.github.webpanimated;
> 
> import com.bumptech.glide.annotation.GlideModule;
> import com.bumptech.glide.module.AppGlideModule;
> 
> @GlideModule
> public class MyGlideModule extends AppGlideModule {
> }
> ```

具体可以参考Glide V4的文档
[https://bumptech.github.io/glide/doc/configuration.html#appglidemodule](https://bumptech.github.io/glide/doc/configuration.html#appglidemodule)

**Comment by shily** [comment]
For someone facing the same issue.

1.  First you should write your own AppGlideModule.
2. If you use kotlin, you should use `kapt` instead of `annotationProcessor`. 

[fix APNG4Android not loaded](https://github.com/shily/APNG4Android-WEBP-BUG/commit/9f01f91f0f93da7ab08d61815fff29bd35849c9d)
