### ISSUE TITLE
How to just get a mini size thumbnail of animated webp

### ISSUE THREAD

**Issue by sareban101** [penfeizhou/APNG4Android#135]
Hi
I want to show a thumbnail of animated webps in recyclerview 
i wrote this:
 `	public Bitmap GetBitmapFromFile(String Dir,String FileName,int Index)
	{
		File file = new File(Dir,FileName);
		
		FileLoader fileLoader = new FileLoader(file.getAbsolutePath());
		final WebPDecoder decoder = new WebPDecoder(fileLoader,null);
		decoder.setLoopLimit(1);
		decoder.setDesiredSize(800, 800);
		decoder.addRenderListener(new FrameSeqDecoder.RenderListener() {

			public void onEnd() {
				
				decoder.stop();
			}

			public void onRender(ByteBuffer arg0) {
				
				
			}

			public void onStart() {
				// TODO Auto-generated method stub
				
			}
		});
		try {
			return decoder.getFrameBitmap(Index);
		} catch (IOException e) {
			
		e.printStackTrace();
			return null;
		}
		frameSeqDecoder.
	}`
And put bitmaps in an arrayList of Bitmaps

it works perfect but somtime 
Failed to allocate a 1048588 byte allocation with 132800 free bytes and 129KB until OOM

how can i get a mini size thumbnail of webp and set it in onBind of recyclerView:

I want to show static images in recycleview

Please Help me

**Comment by jingpeng** [comment]
Hi, when you want to display thumbnails, which frame in an animated webp would you want, the first or the last or certain index in the frames?

**Comment by sareban101** [comment]
just first

**Comment by jingpeng** [comment]
Can you paste your OOM stack here?

**Comment by sareban101** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 1048588 byte allocation with 473192 free bytes and 462KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at com.github.penfeizhou.animation.decode.FrameSeqDecoder.getFrameBitmap(FrameSeqDecoder.java:553)

**Comment by jingpeng** [comment]
you can smaller the desired size

**Comment by sareban101** [comment]
How can I do it?
is it correct?
`decoder.setDesiredSize(imageView.getHeight, imageView.getWidth);`

**Comment by jingpeng** [comment]
Yes, but this size is in pixels, you can try whether exists OOM, if oom still exists, decrease the size but keep the proportion, by the way, how many image views are displayed in a screen

**Comment by sareban101** [comment]
Thank you 
But even when I set the height and width to 400, it still gives the same error

**Comment by jingpeng** [comment]
Do you have a link of your demo project?

**Comment by sareban101** [comment]
thanks a lot
i fixed it by showing png files in onBind with glide

**Comment by CrackerKSR** [comment]
Can anybody tell me how to simply decode the animated webp and iterate each through each frames for getting bitmaps

**Comment by CrackerKSR** [comment]
I get error that getFrameBitmap has protected access

**Comment by CrackerKSR** [comment]
How do we loop through each frames?
we have to use bytebuffer of onRender() ?
please help on this. I need in urgent. This library will save my grass. I am trying to use it in Recat native but noob in java.

**Comment by CrackerKSR** [comment]
> Hi I want to show a thumbnail of animated webps in recyclerview i wrote this: ` public Bitmap GetBitmapFromFile(String Dir,String FileName,int Index) { File file = new File(Dir,FileName);
> 
> ```
> 	FileLoader fileLoader = new FileLoader(file.getAbsolutePath());
> 	final WebPDecoder decoder = new WebPDecoder(fileLoader,null);
> 	decoder.setLoopLimit(1);
> 	decoder.setDesiredSize(800, 800);
> 	decoder.addRenderListener(new FrameSeqDecoder.RenderListener() {
> 
> 		public void onEnd() {
> 			
> 			decoder.stop();
> 		}
> 
> 		public void onRender(ByteBuffer arg0) {
> 			
> 			
> 		}
> 
> 		public void onStart() {
> 			// TODO Auto-generated method stub
> 			
> 		}
> 	});
> 	try {
> 		return decoder.getFrameBitmap(Index);
> 	} catch (IOException e) {
> 		
> 	e.printStackTrace();
> 		return null;
> 	}
> 	frameSeqDecoder.
> }`
> ```
> 
> And put bitmaps in an arrayList of Bitmaps
> 
> it works perfect but somtime Failed to allocate a 1048588 byte allocation with 132800 free bytes and 129KB until OOM
> 
> how can i get a mini size thumbnail of webp and set it in onBind of recyclerView:
> 
> I want to show static images in recycleview
> 
> Please Help me

can we get Frame and FrameBitmap without using listener.

**Comment by CrackerKSR** [comment]
> Do you have a link of your demo project?

@jingpeng I am trying to create a animated image resizer and converter for React Native.  I am having issue with getFrameBitmap inside the onStart().  
Simply I am unable to access frameDuration and frameBitmap in one code block. 
plz help. 

ps: for now I am using decoders of glide to get bitmaps of gif and awebp and encode using apng4 but I want ditch glide and decode using APNG4.
I was able to get bitmaps and duration on onStart by invoking stop method in onStart() itself but it made execution too slow by each new iterations.
