### ISSUE TITLE
setImageDrawable方法会导致大量的ANR!

### ISSUE THREAD

**Issue by ForeverYoungWJ** [penfeizhou/APNG4Android#136]
你好：
       使用ImageView的setImageDrawable方法设置drawable的时候（drawable为APNGDrawable类型），统计后台监控到发生了很多anr的现象。
sdk版本：2.12.0
glide_plug版本：2.12.0
------------------------------------------------------------------------------------------------------------------------
anr traces:
2generate begin time: 2022-01-14 07:48:56
3[DEBUG] dump art internal: 125
4[DEBUG] VMExt: 0x7b5a2a9500, i: 64, str: 4
5[DEBUG] aborting: 0x7b589116d0, 0
6[DEBUG] Dump: 0x0, State: 0x7b5877c7b4, JavaStack: 0x7b58780120
7[DEBUG] current: 0x7b5a2c2a00, pid: 13313
8[DEBUG] List: 0x7b5a2ee000
9[DEBUG] Each: 0x7b58793d1c
10[DEBUG] err: 0x7bdc0329d0
11[DEBUG] begin each
12[DEBUG] dumping 0x7b5a2c2a00 ...
13"main" prio=7 tid=1 Waiting
14  | group="" sCount=0 dsCount=0 flags=0 obj=0x73d54730 self=0x7b5a2c2a00
15  | sysTid=11688 nice=-4 cgrp=default sched=0/0 handle=0x7bdf2b29a8
16  | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
17  | stack=0x7fd7455000-0x7fd7457000 stackSize=8MB
18  | held mutexes=
19  at java.lang.Object.wait(Object.java)
20  - waiting on <0x0a140ffe> (a java.lang.Object)
21  at java.lang.Thread.parkFor$(Thread.java:2137)
22  at sun.misc.Unsafe.park(Unsafe.java:358)
23  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
24  at com.github.penfeizhou.animation.decode.FrameSeqDecoder.getBounds(FrameSeqDecoder.java:236)
25  at com.github.penfeizhou.animation.FrameAnimationDrawable.getIntrinsicWidth(FrameAnimationDrawable.java:253)
26  at android.widget.ImageView.invalidateDrawable(ImageView.java:265)
27  at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:450)
28  at com.github.penfeizhou.animation.FrameAnimationDrawable.invalidateSelf(FrameAnimationDrawable.java:330)
29  at android.graphics.drawable.Drawable.setVisible(Drawable.java:859)
30  at com.github.penfeizhou.animation.FrameAnimationDrawable.setVisible(FrameAnimationDrawable.java:244)
31  at android.widget.ImageView.updateDrawable(ImageView.java:1019)
32  at android.widget.ImageView.setImageDrawable(ImageView.java:567)
33  at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:104)

**Comment by jingpeng** [comment]
请检查下资源正确性，不正确的资源会导致图片宽高无法获取
