### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by Ferdari** [penfeizhou/APNG4Android#137]
### New Issue Checklist

- [X ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | e.g. ZTE BLADE V9, and most Android 9 to lower                             |      |
| System Version               | e.g.  7 to 9                                             |      |
| APNG4Android Library Version | e.g.  2.17                                          |      |
| Repro rate                   | e.g. all the time (100%)   |      |
| Repro with our demo project  | e.g. does it happen with our demo project?            |      |
| Demo project link            |  none |      |

### Issue Description and Steps

Im trying to solve error and to pass error with Try Catch without success, i have hours and days of debugging to check if app is passing a null image but not, it only happens on old Android devices when i load about 30 animated webps in imageviews, on newer version of android is OK.

`Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1114)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1081)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1031)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:992)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.obtainBitmap(FrameSeqDecoder.java:130)
       at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(WebPDecoder.java:146)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(FrameSeqDecoder.java:505)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(FrameSeqDecoder.java:36)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:60)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(FrameSeqDecoder.java:310)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(FrameSeqDecoder.java:36)
       at com.github.penfeizhou.animation.decode.FrameSeqDecoder$9.run(FrameSeqDecoder.java:446)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:240)
       at android.os.HandlerThread.run(HandlerThread.java:67)`

Happens on **FrameSeqDecoder.obtainBitmap**, i have more than 1000 alerts of errors on Crashlytics.

**Comment by penfeizhou** [comment]
What's the old android device's system version?

**Comment by penfeizhou** [comment]
And would you check the file format of web?It looks like when parsing inner frame,it's size turns out to be 0.

**Comment by Ferdari** [comment]
> What's the old android device's system version?
i was mistaken, it occurs also en newer android versions
from 7 to 11
![imagen](https://user-images.githubusercontent.com/14990241/149607393-f8bfcb96-9405-4b65-8ffb-17dcd22ea104.png)

**Comment by penfeizhou** [comment]
> And would you check the file format of web?It looks like when parsing inner frame,it's size turns out to be 0.

It should never happened by the way.

**Comment by Ferdari** [comment]
> And would you check the file format of web?It looks like when parsing inner frame,it's size turns out to be 0.

i rechecked every webp, it works with same files on my LG V50, but not on my ZTE Blade V9.

**Comment by penfeizhou** [comment]
Would you debug and find more information?
Here on `com.github.penfeizhou.animation.webp.decode.AnimationFrame.java` line 32,33
```java
 this.frameWidth = anmfChunk.frameWidth;
 this.frameHeight = anmfChunk.frameHeight;
```
Set a conditional breakpoint and check if this is a parsing problem.
![image](https://user-images.githubusercontent.com/9526211/149607661-e9398598-1dec-4bf0-9a4f-ebaf121ede66.png)

**Comment by Ferdari** [comment]
> Would you debug and find more information? Here on `com.github.penfeizhou.animation.webp.decode.AnimationFrame.java` line 32,33
> 
> ```java
>  this.frameWidth = anmfChunk.frameWidth;
>  this.frameHeight = anmfChunk.frameHeight;
> ```
> 
> Set a conditional breakpoint and check if this is a parsing problem. ![image](https://user-images.githubusercontent.com/9526211/149607661-e9398598-1dec-4bf0-9a4f-ebaf121ede66.png)

Sorry, I dont know how to , im using as AAR in my Library for B4A. 😱

**Comment by penfeizhou** [comment]
This is a 1-based value, from the spec, this should be larger or equal than 1.
Or did you use this library to load a non animated  webp? You can add a bp like below to check.
![image](https://user-images.githubusercontent.com/9526211/149607816-bfb70a2e-34b4-4a16-8358-2acac710c9d8.png)

**Comment by penfeizhou** [comment]
> > Would you debug and find more information? Here on `com.github.penfeizhou.animation.webp.decode.AnimationFrame.java` line 32,33
> > ```java
> >  this.frameWidth = anmfChunk.frameWidth;
> >  this.frameHeight = anmfChunk.frameHeight;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Set a conditional breakpoint and check if this is a parsing problem. ![image](https://user-images.githubusercontent.com/9526211/149607661-e9398598-1dec-4bf0-9a4f-ebaf121ede66.png)
> 
> Sorry, I dont know how to , im using as AAR in my Library for B4A. 😱
> 
> I call your library this way on eclipse:
> 
> ```
> 	public Drawable LoadWEBPanimated(String file) {
> 
> 		try {
> 		Drawable drawable = null;
> 		drawable = WebPDrawable.fromFile(file);
> 		
> 		return drawable;
> 		}catch (Exception e) {
> 			BA.LogError(e.getMessage());
> 			return null;  
>         }
> 	}
> ```

em, I think this happends when loading an non animated webp.

**Comment by Ferdari** [comment]
> > > Would you debug and find more information? Here on `com.github.penfeizhou.animation.webp.decode.AnimationFrame.java` line 32,33
> > > ```java
> > >  this.frameWidth = anmfChunk.frameWidth;
> > >  this.frameHeight = anmfChunk.frameHeight;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Set a conditional breakpoint and check if this is a parsing problem. ![image](https://user-images.githubusercontent.com/9526211/149607661-e9398598-1dec-4bf0-9a4f-ebaf121ede66.png)
> > 
> > 
> > Sorry, I dont know how to , im using as AAR in my Library for B4A. 😱
> > I call your library this way on eclipse:
> > ```
> > 	public Drawable LoadWEBPanimated(String file) {
> > 
> > 		try {
> > 		Drawable drawable = null;
> > 		drawable = WebPDrawable.fromFile(file);
> > 		
> > 		return drawable;
> > 		}catch (Exception e) {
> > 			BA.LogError(e.getMessage());
> > 			return null;  
> >         }
> > 	}
> > ```
> 
> em, I think this happends when loading an non animated webp.

In B4A(Basic language) i check if is it an Animated Webp this way before loading with APNG lib:
`Sub IsWebpAnimated(Path As String, Webp As String) As Boolean
	Try
		If File.Exists(Path,Webp) Then
			Dim wf As String=File.ReadString(Path,Webp)
			If wf.Contains("ANMF") Then
				Return True
			Else
				Return False
			End If
		End If
	Catch
		Log(LastException)
		Return False
	End Try
End Sub`

So it should be an animated Webp

**Comment by penfeizhou** [comment]
It looks like when system decoding webp file, the options.outWidth or options.outHeight return 0.
```java
if (!anim) {
            if (!vp8x) {
                BitmapFactory.Options options = new BitmapFactory.Options();
                options.inJustDecodeBounds = true;
                BitmapFactory.decodeStream(reader.toInputStream(), null, options);
                canvasWidth = options.outWidth;
                canvasHeight = options.outHeight;
            }
            frames.add(new StillFrame(reader, canvasWidth, canvasHeight));
            this.loopCount = 1;
        }
```

**Comment by penfeizhou** [comment]
> 

You can  use `WebPParser.isAWebP` to check if this is awebp

**Comment by Ferdari** [comment]
> 

What can be?

also i need to say the app shows ok the 30 imageviews and plays ok, but in some seconds playing activity crash with error.

**Comment by Ferdari** [comment]
> > 
> 
> You can use `WebPParser.isAWebP` to check if this is awebp

Im already checking with own function, also check every file are animated webps and size more than 0kb

**Comment by penfeizhou** [comment]
What I can do right now is add some protection to avoid crash at least

**Comment by penfeizhou** [comment]
You can try `v2.17.1`

**Comment by Ferdari** [comment]
> You can try `v2.17.1`

Thanks @penfeizhou , can you share de AAR file to compile my wrapper. thanks again.

**Comment by penfeizhou** [comment]
It's hosted in mavencentral,you can download it later.

**Comment by Ferdari** [comment]
> mavencentral

thanks, ill be pending.

**Comment by Ferdari** [comment]
I tested your update but the problem still there:

It appears that the problem is in **FrameSeqDecoder.java:130** but you only modified **FrameAnimationDrawable.java**

Still having same issue😱

**Comment by Ferdari** [comment]
Any news?

**Comment by jingpeng** [comment]
> Any news?

Can you provide the problem webp image which may cause this issue?

**Comment by Ferdari** [comment]
> 

 if you read this thread, it appears it is a problem on low end devices not processing all frames when having a up to 30 images playing.

**Comment by Ferdari** [comment]
Maybe adding more protection to **FrameSeqDecoder.java**, so app don't crash.

**Comment by Ferdari** [comment]
> It means in your case, frame's width and height is less than 0. I thought it was zero before.

my webps are 128x128px, frame by frame

**Comment by penfeizhou** [comment]
> > It means in your case, frame's width and height is less than 0. I thought it was zero before.
> 
> my webps are 128x128px, frame by frame

That‘s not what turns out when it was parsed.

**Comment by Ferdari** [comment]
> > > It means in your case, frame's width and height is less than 0. I thought it was zero before.
> > 
> > 
> > my webps are 128x128px, frame by frame
> 
> That‘s not what turns out when it was parsed.

Can it be a processor error? it only happen on low end devices with up to 30 imageviews playing

**Comment by Ferdari** [comment]
Im thinking the activity thread pauses doing another tasks but APNG4Android still working and cant draw frames. im not sure

**Comment by penfeizhou** [comment]
When parsing WebP formats, there is no relation to android platform api.
And according to [webp spec](https://developers.google.com/speed/webp/docs/riff_container#metadata), the width and height cannot be less than 1.Because this is a unsigned value.
```
Canvas Width Minus One: 24 bits
1-based width of the canvas in pixels. The actual canvas width is '1 + Canvas Width Minus One'
Canvas Height Minus One: 24 bits
1-based height of the canvas in pixels. The actual canvas height is '1 + Canvas Height Minus One'
```
This could only happen when there is no ANIM Chunk, this library treats it as non animated webp. In this case, it calls platform api to get width and height.
```java
if (!anim) {
            //静态图
            if (!vp8x) {
                BitmapFactory.Options options = new BitmapFactory.Options();
                options.inJustDecodeBounds = true;
                BitmapFactory.decodeStream(reader.toInputStream(), null, options);
                canvasWidth = options.outWidth;
                canvasHeight = options.outHeight;
            }
            frames.add(new StillFrame(reader, canvasWidth, canvasHeight));
            this.loopCount = 1;
        }
```

**Comment by penfeizhou** [comment]
v2.17.2, I added protection for case when frame's width and height be less or equal than 0

**Comment by Ferdari** [comment]
> v2.17.2, I added protection for case when frame's width and height be less or equal than 0

Im testing, thanks for the edit.

**Comment by Ferdari** [comment]
Hi again, after testing the new version, there is still the same problem,

Checking my webp files, i found one that is causing this bug, if webp has a transparent frame or blank frame it causes error **width and height must be > 0** even if it has same height and width:
![imagen](https://user-images.githubusercontent.com/14990241/150282353-d2903850-e121-4e6d-8d9e-211a4797124d.png)
Look at first frame, it are blank frame/transparent frame, if use it in my app, app crashes(only on some phones).

But if i delete blank frame it work like charm in app, so the problem is in some devices blank frames are detected without size.

Affected webp:
https://cdn.noten.in/temp/badwebp.webp ❌
https://cdn.noten.in/temp/goodwebp.webp ✔️

**Comment by jingpeng** [comment]
@Ferdari Can you debug on your phone which may crash under bad webp? To position this bug, you can setup your breakpoint on ANMFChunk.java line 100 & see the decoded frameWidth & frameHeight

**Comment by Ferdari** [comment]
> @Ferdari Can you debug on your phone which may crash under bad webp? To position this bug, you can setup your breakpoint on ANMFChunk.java line 100 & see the decoded frameWidth & frameHeight. Of course the info of the first frame

Im sorry i dont use Android studio, i use B4A IDE for app, and i created a java library(on eclipse) to use in.
```public Drawable LoadWEBPanimated(String file) {
		try {
		Drawable drawable = null;
		drawable = WebPDrawable.fromFile(file);
		
		return drawable;
		}catch (Exception e) {
			BA.LogError(e.getMessage());
			return null; 
        }
	}
```
I use APNG4Droid with only one call:

**Comment by jingpeng** [comment]
can you provide your genymotion version & vm version, I 'll download it & check because my mi 9 pro 5g cannot reproduce it

**Comment by Ferdari** [comment]
Hi, im using Genymotion v 3.2.1 + VirtualBox 6.1 + Huawei P30 Virtual device Android 9

Logs:
[genymotion-logs-20220121-115114.zip](https://github.com/penfeizhou/APNG4Android/files/7915714/genymotion-logs-20220121-115114.zip)

**Comment by jingpeng** [comment]
> Hi, im using Genymotion v 3.2.1 + VirtualBox 6.1 + Huawei P30 Virtual device Android 9 installed from Genymotion.
> 
> Logs: [genymotion-logs-20220121-115114.zip](https://github.com/penfeizhou/APNG4Android/files/7915714/genymotion-logs-20220121-115114.zip)
<img width="439" alt="截屏2022-01-25 下午5 17 12" src="https://user-images.githubusercontent.com/5223226/150947872-30ebc3b6-1528-4f4c-9d36-62e4f07e9392.png">
For i use the same version environment & display the badwebp.webp, but it seems run perfectly

**Comment by jingpeng** [comment]
So, I doubt perhaps the B4A framework affect this

**Comment by Ferdari** [comment]
> So, I doubt perhaps the B4A framework affect this

Im checkiing, are you sure you are using Badwebp?

**Comment by jingpeng** [comment]
Yes, i am sure
