### ISSUE TITLE
load apng url  can not work 

### ISSUE THREAD

**Issue by yukuoyuan** [penfeizhou/APNG4Android#139]
Glide.with(this).load("https://a.xnimg.cn/wap/mobile/wxMiniApp/onlineImgs/undercover_header/headerbg.png")
            .set(AnimationDecoderOption.DISABLE_ANIMATION_APNG_DECODER, true)
            .into(viewBinding?.ivItemTestBanner!!)

    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.16.0'
    implementation 'com.github.penfeizhou.android.animation:apng:2.16.0'

The picture animation not work

**Comment by penfeizhou** [comment]
`AnimationDecoderOption.DISABLE_ANIMATION_APNG_DECODER`
If you set this flag to true, the apng decoder won't work.

**Comment by yukuoyuan** [comment]
Glide.with(this).load("https://a.xnimg.cn/wap/mobile/wxMiniApp/onlineImgs/undercover_header/headerbg.png")
            .into(viewBinding?.ivItemTestBanner!!)


when i use it  it same not work

**Comment by yukuoyuan** [comment]
如何 加载url apng 图片啊?老铁 我这边加载不行啊,都是静态图,不会动

**Comment by yukuoyuan** [comment]
@GlideModule
public class MyGlideModule extends AppGlideModule {
}

add the code ,it work ok
