### ISSUE TITLE
Why is Gif support enabled in Glide integration? / Wrong Javadoc in AnimationDecoderOption 

### ISSUE THREAD

**Issue by connyduck** [penfeizhou/APNG4Android#141]
Jacadoc says `Defaults to {@code true}` when it clearly defaults to false.

https://github.com/penfeizhou/APNG4Android/blob/a4a7a513f0535ce753757f8db9f4009adcabf154/plugin_glide/src/main/java/com/github/penfeizhou/animation/glide/AnimationDecoderOption.java#L12-L17

I think the Javadoc is right here - it makes no sense to enable Gif support when Glide can do this already without this library.

**Comment by penfeizhou** [comment]
It was set to true before，But now this was set to false. The java doc was missed while changing. This library uses native code to decode gif file for better performance.

**Comment by connyduck** [comment]
I see. Well your Gif support seems to be buggy, see [here](https://github.com/tuskyapp/Tusky/issues/2366). It works with Glide's Gif implementationö

**Comment by penfeizhou** [comment]
> I see. Well your Gif support seems to be buggy, see [here](https://github.com/tuskyapp/Tusky/issues/2366). It works with Glide's Gif implementation.

Let me see, can you provide the url  with the problemed file to help me fix this？

**Comment by penfeizhou** [comment]
> https://cdn.social.linux.pizza/v1/AUTH_91eb37814936490c95da7b85993cc2ff/sociallinuxpizza/accounts/avatars/107/744/247/345/586/620/original/4a94ce749868d347.gif

The problem is due to gif decoder's disposal action. And I've fixed it on https://github.com/penfeizhou/APNG4Android/commit/68bcff8ebf801eb54af95085f8863f6264bf35fe.
You can  try this version `v2.19.0` should fix this problem.

**Comment by connyduck** [comment]
It works, thx! You tagged 2.19.0 but you published 2.18.0 to Maven Central though

**Comment by penfeizhou** [comment]
> It works, thx! You tagged 2.19.0 but you published 2.18.0 to Maven Central though

The version was mistaken. Please try this.
