### ISSUE TITLE
Encode deocde animated awebp to get bitmaps. 

### ISSUE THREAD

**Issue by CrackerKSR** [penfeizhou/APNG4Android#143]
I just found this repo after lots of search for encoder decoder for my use case. I am sorry if this is not appropriet way or basic question 
I want to decoe animated webp and iterate over each bitmaps.
Please help.

I found this snippet from issue but here. It is used for raising issue so this code would not work properly

```java
  drawable = ApngDrawable.decode(getInputStream(uri))
  val encoder = WebPEncoder()
  for (frameNum in 0 until drawable.frameCount) {
      drawable.seekToFrame(0, frameNum)
      var frame = scaleToAlternative(drawableToBitmap(drawable.current)!!, 512, 512, 16)
      encoder.addFrame(frame, 0, 0, drawable.frameDurations[frameNum])
  }
  createFile(encoder.build(), path) 
```

Please tell how to decoded encode gif and awebp in above way. 
I can see all thoe classes but what is the proper way I do not know. Please help

**Comment by CrackerKSR** [comment]
@penfeizhou Please help. It will take too much time to study all this. You can tell me the classes and methods to decode at least for iterateing through webp frames as bitmap. Only this would be enough. I have webp encoder I will use these bitmaps to resize and encode all them into awebp using a webp encoder I have.

**Comment by penfeizhou** [comment]
If you want decode apng and encode into animated webp,
you could try following code
```java
new Thread(new Runnable() {
            @Override
            public void run() {

                final byte[] ret = WebPEncoder.fromDecoder(
                        APNGDrawable.fromAsset(EncoderTestActivity.this,
                                "test2.png").getFrameSeqDecoder()).build();
                imageView.post(new Runnable() {
                    @Override
                    public void run() {
                        Glide.with(imageView)
                                .load(ret)
                                .into(imageView);
                    }
                });
            }
        }).start();
```

And you can get every frame's bitmap by `FrameSeqDecoder`'s `getFrameBitmap`.

Please try this on the latest version.

**Comment by CrackerKSR** [comment]
Thanks for response. I want to decode animated webp and I don't want to display over views.

Yeah I have latest version

**Comment by penfeizhou** [comment]
This is what this library is for, and  you can get every frame's bitmap from a animated webp.

**Comment by CrackerKSR** [comment]
Can we get Total duration ? 
or I just need to sum all single duration to get total duration.
