### ISSUE TITLE
有哪些情况会影响apng动画?

### ISSUE THREAD

**Issue by liuhuan8986** [penfeizhou/APNG4Android#144]
您好有一个问题想请教一下， 我之前使用这个库没问题的，后来项目里加了挺多的第三方依赖啥的，某一天发现，apng不会动了，但是我在demo上却是可以动的，所以想请教一下，哪些情况下会影响到这个apng动画

**Comment by jingpeng** [comment]
glide插件会影响这个

**Comment by liuhuan8986** [comment]
发现问题了，之前使用的是 annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
但是项目改动了之后，需要使用 kapt 'com.github.bumptech.glide:compiler:4.12.0'
