### ISSUE TITLE
怎么修改色块的颜色呢？

### ISSUE THREAD

**Issue by q88qaz** [penfeizhou/APNG4Android#146]
怎么修改色块的颜色呢？
我的动画是某个颜色的色块拼接动画，我想换成另一个颜色

**Comment by jingpeng** [comment]
能举这个图的例子来说明下你的需求么

**Comment by q88qaz** [comment]
布局文件内中给ImageView设置android:tint="#778899"
发现设置后，apng播放起来还是原来的颜色，并不是设置的颜色#778899

**Comment by jingpeng** [comment]
这个设置针对于本库是无效的

**Comment by q88qaz** [comment]
那我想要针对本库设置有效的方法

**Comment by penfeizhou** [comment]
不支持这个属性

**Comment by q88qaz** [comment]
蚌埠住了
