### ISSUE TITLE
加载为圆形图片失效 

### ISSUE THREAD

**Issue by yukuoyuan** [penfeizhou/APNG4Android#147]
加载的图片链接为 http://rrfmn.rrimg.com/fmn41002/20211104/1530/head_ee7c0d3ef35cffcc463395d25ec41575.jpg

**Comment by penfeizhou** [comment]
请描述清晰问题，提供代码

**Comment by yukuoyuan** [comment]
Glide.with(this).load("http://rrfmn.rrimg.com/fmn41002/20211104/1530/head_ee7c0d3ef35cffcc463395d25ec41575.jpg")
            .circleCrop()
            .error(com.donews.renren.android.lib.base.R.drawable.common_default_head)
            .placeholder(com.donews.renren.android.lib.base.R.drawable.common_default_head)
            .into(imageView)


展示为方形的,应该是圆形才对

**Comment by penfeizhou** [comment]
你这个是jpg图片，跟这个库没关系。

**Comment by penfeizhou** [comment]
另外，glide的transform只对bitmap对象生效，本库并不是bitmap，所以也不会生效。

**Comment by yukuoyuan** [comment]
如果不使用本库 glide 加载是没有问题的

**Comment by penfeizhou** [comment]
你这个链接虽然后缀名是jpg,但实际是GIF格式,还是在用本库解码.
可以设置disable本库的解码器,使用默认的GIF解码器
```java
 GlideApp.with(imageView)
                    .load(url)
                    .circleCrop()
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, true)
                    .into(imageView);
```

**Comment by yukuoyuan** [comment]
可以了 感谢,抱歉了
