### ISSUE TITLE
Dependency to https://dl.bintray.com/osborn/Android

### ISSUE THREAD

**Issue by stom79** [penfeizhou/APNG4Android#15]
I am using your library with my application and I am pretty happy with it. Recently, [FDroid build failed](https://f-droid.org/wiki/page/fr.gouv.etalab.mastodon/lastbuild_297) due to the dependency to `https://dl.bintray.com/osborn/Android`
What would be the best way to remove this dependency? Thanks for helping

**Comment by stom79** [comment]
I downgraded the lib to 0.2.8 and the dependency is no longer needed. 

`implementation 'com.github.penfeizhou.APNG4Android:glide-plugin:0.2.8'`

**Comment by penfeizhou** [comment]
Hi there,the library is included in jcenter.You do not need to add the maven repository https://dl.bintray.com/osborn/Android. Just the jcenter is ok.
```gradle
    repositories {
        jcenter()
    }
```

**Comment by stom79** [comment]
Thanks! But it fails though I defined jcenter:
https://framagit.org/tom79/fedilab/blob/develop/build.gradle#L18

**Comment by penfeizhou** [comment]
Thank you for your reminding.I'll fix this soon

**Comment by stom79** [comment]
Thanks a lot!
