### ISSUE TITLE
怎么操作网络gif图片，视乎都仅仅只支持本地的。

### ISSUE THREAD

**Issue by GuoLiangjun123** [penfeizhou/APNG4Android#150]
1.如题  2.我添加了gilde插件com.github.penfeizhou.android.animation:glide-plugin:2.21.0，但是无法使用

**Comment by penfeizhou** [comment]
1. 文档里给出的例子就是一张网络图片 Glide.with(imageView).load("https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp").into(imageView);
2. 关于Glide插件为什么不生效,请查看Glide文档

**Comment by GuoLiangjun123** [comment]
> 1. 文档里给出的例子就是一张网络图片 Glide.with(imageView).load("[https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp").into(imageView](https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp%22).into(imageView));
> 2. 关于Glide插件为什么不生效,请查看Glide文档

那个列子不就是直接用的glide加载图片吗，那跟您的库还有什么关系呢
