### ISSUE TITLE
Load/Unload Glide module at any moment

### ISSUE THREAD

**Issue by captainepoch** [penfeizhou/APNG4Android#151]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

I would like to know if it is possible to load/unload this module at any moment. For example, let's say I want to animate apng files only when an user enables that feature in the Preferences section of the application.

Thank you!

**Comment by jingpeng** [comment]
You can control the animation manually without glide, create an APNGDrawable and control it to start playing or stop playing

**Comment by penfeizhou** [comment]
This could be done using glide like this:
```java
GlideApp.with(imageView)
                    .load(url)
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, flag)
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_WEBP_DECODER, flag)
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_APNG_DECODER, flag)
                    .into(imageView);
```
If `flag` is set to true, the animation module will not work, false otherwise.

**Comment by captainepoch** [comment]
That seems to be working perfectly, thank you!
