### ISSUE TITLE
Frame rate speed functionality

### ISSUE THREAD

**Issue by Borgran** [penfeizhou/APNG4Android#152]
Hi, 
thanks for you work! Great addon.

I am missing a function - could you add frame rate speed change support or simple skip frame function.
I have checked your Frame Sequencer but there is only option to stop/start/pause frames. 

Cheers
PB

**Comment by CrackerKSR** [comment]
> ```java
> getFrameCount
> ```

Hi, I tried to acces FrameCount but it gives 0 also tried to get Frame duration but it throws null object error. What am I missing..

```java
FrameSeqDecoder decoder = GifDrawable.fromFile(path).getFrameSeqDecoder();
    if (decoder != null){
      int frameCount = decoder.getFrameCount();
      android.util.Log.d("ReactNative","frameCount: " + frameCount);
      // int duration = decoder.getFrame(0).frameDuration;
      // android.util.Log.d("ReactNative","duration: " + duration);
    }
```
