### ISSUE TITLE
非正常apng图片(被识别为apng)，解析出现异常后，不抛出异常

### ISSUE THREAD

**Issue by AlvinScrp** [penfeizhou/APNG4Android#154]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | 与设备无关                            |      |
| System Version               | 与系统版本无关                                         |      |
| APNG4Android Library Version |  2.22.0                                           |      |
| Repro rate                   | all the time (100%)    |      |

### Issue Description and Steps

我有一张图片
https://cdn.webuy.ai/others/assets/img/2022/06/07/8f11576d-d3ce-486a-95df-9f1e068ffc66____size702x200.png

图片为非正常的apng格式，但是`APNGParser.isAPNG()`结果为true，
而在`APNGParser.parse()`过程中会抛出`IOException`,
> java.io.IOException: Out of chunk area

问题：
1）如何更好的识别APNG图片，特别是数据异常的APNG图片
2）能否提供一个异常的回调，能够让应用二次处理

**Comment by penfeizhou** [comment]
1. 可以通过获取帧数判断是否正常解码
```java   
public int getFrameCount();
```
2. Decoder这一层没有异常的回调, 异常的图片不能展示,应用可以自行进行如1的判断后再二次处理

**Comment by AlvinScrp** [comment]
好的，谢谢

**Comment by wustwg** [comment]
> 1. 可以通过获取帧数判断是否正常解码
> 
> public int getFrameCount();
> 2. Decoder这一层没有异常的回调, 异常的图片不能展示,应用可以自行进行如1的判断后再二次处理

请问 我本地文件是正常的，在调用 com.github.penfeizhou.animation.gif.GifDrawable gifDrawable = com.github.penfeizhou.animation.gif.GifDrawable.fromFile(file.getAbsolutePath());
//                if (gifDrawable.getFrameSeqDecoder().getFrameCount() == 0) {
//                    throw new Exception("GifDrawable frameCount is 0");
//                } 解析之后，立即获取帧数，返回的始终是0 这是为什么？文件时正常的 ，注释掉getFrameCount 这个可以正常渲染。
