### ISSUE TITLE
能否指定播放进度

### ISSUE THREAD

**Issue by oooo7777777** [penfeizhou/APNG4Android#155]
一张30帧的图片，我通过手势控制播放进度

**Comment by oooo7777777** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CrackerKSR** [comment]
> 如果要自己控制进度,建议你是直接通过获取FrameSeqDecoder调用下面的API获取位图渲染
> 
> ```java
>  /**
>      * Get Indexed frame
>      *
>      * @param index <0 means reverse from last index
>      */
>     public Bitmap getFrameBitmap(int index) throws IOException;
> ```

@penfeizhou  This returns null in onStart() 
But it returns desired bitamp in onEnd() but that slows down the execution by each iteration. please help

**Comment by initialjie** [comment]
> 

> > 如果要自己控制进度,建议你是直接通过获取FrameSeqDecoder调用下面的API获取位图渲染
> > ```java
> >  /**
> >      * Get Indexed frame
> >      *
> >      * @param index <0 means reverse from last index
> >      */
> >     public Bitmap getFrameBitmap(int index) throws IOException;
> > ```
> 
> @penfeizhou This returns null in onStart() But it returns desired bitamp in onEnd() but that slows down the execution by each iteration. please help

方案缺少了可以从关键 frame 渲染的算法，所以总是从第 0 个 frame 开始渲染。
当需要从某个 frame 开始播放或者获取某个 frame 的 bitmap 时，效率比较低，每次都需要从 0 开始迭代。
