### ISSUE TITLE
bugly后台统计到内存溢出异常信息。

### ISSUE THREAD

**Issue by bozaixing** [penfeizhou/APNG4Android#156]
<html>
<body>

--------- beginning of crash
--
9206-21 18:17:02.266 7523 28914 E AndroidRuntime: FATAL EXCEPTION: FrameDecoderExecutor-3
9306-21 18:17:02.266 7523 28914 E AndroidRuntime: Process: com.fbx.handwriteime, PID: 7523
9406-21 18:17:02.266 7523 28914 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 3025752 byte allocation with 2175968 free bytes and 2124KB until OOM, target footprint 536870912, growth limit 536870912
9506-21 18:17:02.266 7523 28914 E AndroidRuntime: at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
9606-21 18:17:02.266 7523 28914 E AndroidRuntime: at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
9706-21 18:17:02.266 7523 28914 E AndroidRuntime: at java.nio.ByteBuffer.allocate(ByteBuffer.java:282)
9806-21 18:17:02.266 7523 28914 E AndroidRuntime: at com.github.penfeizhou.animation.decode.FrameSeqDecoder.C(SourceFile:2)
9906-21 18:17:02.266 7523 28914 E AndroidRuntime: at com.github.penfeizhou.animation.decode.FrameSeqDecoder.l(SourceFile:1)
10006-21 18:17:02.266 7523 28914 E AndroidRuntime: at com.github.penfeizhou.animation.decode.FrameSeqDecoder$e.run(SourceFile:5)
10106-21 18:17:02.266 7523 28914 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
10206-21 18:17:02.266 7523 28914 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
10306-21 18:17:02.266 7523 28914 E AndroidRuntime: at android.os.Looper.loop(Looper.java:257)
10406-21 18:17:02.266 7523 28914 E AndroidRuntime: at android.os.HandlerThread.run(HandlerThread.java:67)
10506-21 18:17:02.429 7523 28914 E memtrack: Couldn't load memtrack module
10606-21 18:17:03.152 7523 7523 I bx.handwriteim: Waiting for a blocking GC Alloc
![微信图片_20220621183658](https://user-images.githubusercontent.com/4454438/174780901-34c787ca-7d18-4f6d-ad0c-355dc3549e53.png)

10706-21 18:17:03.156 7523 28914 I bx.handwriteim: Waiting for a blocking GC Alloc

</body>
</html>

**Comment by penfeizhou** [comment]
应用内存耗尽,库是没办法正常工作的.

**Comment by bozaixing** [comment]
好的，谢谢。
