### ISSUE TITLE
您好，使用了apng的glide插件无效，加载后不执行动画

### ISSUE THREAD

**Issue by kiss718867** [penfeizhou/APNG4Android#157]
gradle配置如下：

   implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
    implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.9.0'
    implementation 'com.github.penfeizhou.android.animation:apng:2.9.0'

Java代码如下：
         ImageView imageView = view.findViewById(R.id.iv);
         GlideApp.with(imageView)
                 .load(str)
                 .into(imageView);

**Comment by jingpeng** [comment]
首先确保用最新版本，2.23.0，另外遵循文档Glide.with(imageView).load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png").into(imageView);
