### ISSUE TITLE
无法加载本地jpg大图，图片大小12.9M

### ISSUE THREAD

**Issue by Youngkkk** [penfeizhou/APNG4Android#158]
测试页面：demo中的APNGTestActivity
替换urls为本地图片路径，删掉.set(AnimationDecoderOption.NO_ANIMATION_BOUNDS_MEASURE, true)，删掉GlideAnimationModule中的registry.register(FrameSeqDecoder.class, Drawable.class, new FrameDrawableTranscoder());才能加载本地大图（静态图片为.jpg），图片的小12.9M。不然只能展示图片顶部一小部分图片，小图展示没问题

**Comment by penfeizhou** [comment]
jpg图片不会使用本库解码器，请贴一下问题图片

**Comment by Youngkkk** [comment]
图片地址如下：
28M:https://1drv.ms/u/s!AsxpT3zHGhsfo328lNocLV42UAvV
13M:https://1drv.ms/u/s!AsxpT3zHGhsfo3y9Q8zyXus91wgH

**Comment by Youngkkk** [comment]
问题是将图片保存到本地相册，通过本地路径打开图片会出现展示不全，图片通过在线链接打开没问题

**Comment by Youngkkk** [comment]
辛苦大佬帮忙查看下

**Comment by jingpeng** [comment]
<img width="672" alt="截屏2022-07-21 20 54 12" src="https://user-images.githubusercontent.com/5223226/180218276-232334e2-2160-4502-82ac-e6d9141fb25c.png">
这个大图不是JPG，是PNG

**Comment by jingpeng** [comment]
用本库加载是没有问题的

**Comment by jingpeng** [comment]
![image](https://user-images.githubusercontent.com/5223226/180219019-e7609fc2-a1c5-4fd0-a78c-7435bfa51378.png)

**Comment by Youngkkk** [comment]
是加载本地相册里面的吗？不是通过url加载，我是保存到本地相册的时候，通过本地路径访问才有问题。如果没问题，是怎么调用的呢？

**Comment by jingpeng** [comment]
我是加载本地文件的

**Comment by Youngkkk** [comment]
![12](https://user-images.githubusercontent.com/35022285/180227471-0562e4d1-7215-425b-a7d2-70498993482c.png)
![13](https://user-images.githubusercontent.com/35022285/180227498-0804da54-500e-4411-a812-33503f76b3dc.png)
![14](https://user-images.githubusercontent.com/35022285/180227576-6ff6aa08-e786-45f2-897c-e648dd2ba2d3.png)
目前我这边只注释这一行代码就能展示

**Comment by Youngkkk** [comment]
因为已经缓存了本地磁盘图片，每次运行我都是卸载再运行的

**Comment by jingpeng** [comment]
你同时打开这么多大图会不会OOM内存不足了，单个的话你可以试试

**Comment by jingpeng** [comment]
我的手机小米9 Pro 5G，配置8+256也只能同时展示2张图，再多就OOM了

**Comment by Youngkkk** [comment]
单个还是一样的，只能显示顶部一小部分，我看了存在本地glide根据参数解码之后的磁盘缓存图片也是有问题
![WX20220722-102249](https://user-images.githubusercontent.com/35022285/180348954-0ff765cb-69e5-496e-80f3-e6aa5a50b125.png)
的

**Comment by jingpeng** [comment]
那你删了缓存重新来也是一样么

**Comment by Youngkkk** [comment]
对的，只能删除那行代码，并且清理缓存之后才能恢复

**Comment by jingpeng** [comment]
我这里复现了，看起来是glide的问题，升级glide到4.13.2试试

**Comment by Youngkkk** [comment]
升级了还是不好使，应该本glide的版本没关系

**Comment by jingpeng** [comment]
升级了清缓存我这里就好了

**Comment by Youngkkk** [comment]
我卸载确实好了，谢了
