### ISSUE TITLE
android 9 SIGSEGV(SEGV_MAPERR):

### ISSUE THREAD

**Issue by xiaozhuQQ** [penfeizhou/APNG4Android#161]
Android9 ，集中在小米的一些机型上
SIGSEGV(SEGV_MAPERR):
2
#00 pc 00000000004183b8 /system/lib64/libhwui.so (SkPixelRef::callGenIDChangeListeners()+72) [arm64-v8a::f7a509b837281a546e3b2d5ae9945bc4]
3
#01 pc 00000000003b7514 /system/lib64/libhwui.so (SkBitmap::notifyPixelsChanged() const+24) [arm64-v8a::f7a509b837281a546e3b2d5ae9945bc4]
4
#02 pc 0000000000145664 /system/lib64/libandroid_runtime.so [arm64-v8a::834b7740d8484a3f17c80c975182dc32]
5
#03 pc 0000000000000ef4 /system/framework/arm64/boot-framework.oat [arm64-v8a::04454b44b3cc6c9ed150e8765ffe17be]
6
java:
7
android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:628)

FrameAnimationDrawable.java 
render方法 调用bitmap.copyPixelsFromBuffer(byteBuffer);

**Comment by jingpeng** [comment]
看起来是机型内存问题

**Comment by ShowMeThe** [comment]
这个应该是OOM了
