### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ttdazi** [penfeizhou/APNG4Android#162]
hi @penfeizhou

  java.util.ConcurrentModificationException'
  java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)'
  java.util.HashMap$KeyIterator.next(HashMap.java:1465)'
  com.github.penfeizhou.animation.FrameAnimationDrawable.invalidateSelf(FrameAnimationDrawable.java:2)'
  com.github.penfeizhou.animation.FrameAnimationDrawable.invalidateRunnable.run(FrameAnimationDrawable.java:1)'
  android.os.Handler.handleCallback(Handler.java:938)'
  android.os.Handler.dispatchMessage(Handler.java:99)'
  android.os.Looper.loop(Looper.java:223)'
  android.app.ActivityThread.main(ActivityThread.java:7664)'
  java.lang.reflect.Method.invoke(Native Method)'
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)'
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

sdk：com.github.penfeizhou.android.animation:awebp:2.23.0  

From log analysis, it should be obtainedCallbacks

**Comment by penfeizhou** [comment]
I add some protection in this commit: https://github.com/penfeizhou/APNG4Android/commit/1911afddfde2e7790d2d363eb955b8c836685587
