### ISSUE TITLE
Buffer not large enough for pixels

### ISSUE THREAD

**Issue by chenyunecjtu** [penfeizhou/APNG4Android#165]
### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | e. Huawei JSN-AL00a                               |      |
| System Version               | 10                                         |      |
| APNG4Android Library Version | 2.23.0                                          |      |
| Repro rate                   | e.g. all the time (100%) / sometimes x% / only once   |      |
| Repro with our demo project  | e.g. does it happen with our demo project?            |      |

### Issue Description and Steps

```
java.lang.RuntimeException: Buffer not large enough for pixels
at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:771)
at com.github.penfeizhou.animation.webp.decode.WebPDecoder.renderFrame(SourceFile:6)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder.step(SourceFile:6)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$200(SourceFile:1)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(SourceFile:4)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart(SourceFile:14)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$900(SourceFile:1)
at com.github.penfeizhou.animation.decode.FrameSeqDecoder$6.run(SourceFile:1)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by chenyunecjtu** [comment]
![image](https://user-images.githubusercontent.com/6322749/189280127-2c12784e-9cb2-4f79-b922-8d990c760b26.png)
猜测是sampleSize改变的同时，渲染也在进行，并发导致的？

**Comment by chenyunecjtu** [comment]
![image](https://user-images.githubusercontent.com/6322749/189295238-94242a98-dce3-4075-89c2-55ca71ec9948.png)
麻烦帮忙看下，这样改是否要好点，在samplesize改变的同时，如果渲染也在运行，会出现迸发

**Comment by penfeizhou** [comment]
是的,这个确实可能存在问题

**Comment by penfeizhou** [comment]
修改: https://github.com/penfeizhou/APNG4Android/commit/e8f8fd3a5a9dfffe6151b922a76a61edd0a3609c

**Comment by ShowMeThe** [comment]
这个问题还是存在 我这个也是临时修改的
```
    private AtomicBoolean mSampleSizeChanged = new AtomicBoolean(false);
    public boolean setDesiredSize(int width, int height) {
        mSampleSizeChanged.set(false);
        final int sample = getDesiredSample(width, height);
        if (sample != this.sampleSize) {
            final boolean tempRunning = isRunning();
            workerHandler.removeCallbacks(renderTask);
            workerHandler.post(new Runnable() {
                @Override
                public void run() {
                    mSampleSizeChanged.set(true);
                    innerStop();
                    try {
                        sampleSize = sample;
                        initCanvasBounds(read(getReader(mLoader.obtain())));
                        if (tempRunning) {
                            innerStart();
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            });
        }
        return mSampleSizeChanged.get();
    }
```

**Comment by captainepoch** [comment]
Would @ShowMeThe latest comment fix the issue?

**Comment by zaishi24** [comment]
问题在某些性能不足的手机仍然存在，主要原因是在setDesiredSize中，sampleSizeChanged的修改放置在工作线程中，使得当drawable的setbounds来得比较滞后的情况，就会导致setbounds无法获知sampleSizeChanged的实时变化，使得bitmap的内存大小仍然是较大的值

**Comment by captainepoch** [comment]
Can't it be executed in other thread? Main thread is supposed for only UI/UX stuff, but for calculations that require more computing power, it shouldn't be used.
