### ISSUE TITLE
9.0以下动图WebP加载性能问题

### ISSUE THREAD

**Issue by BoY1506** [penfeizhou/APNG4Android#169]
你好，我在手机上加载动图列表的场景下，测试了Android9.0以下用默认glide加载gif和使用该库加载动图webp，cpu上后者比前者大10%左右，内存占用后者比前者大30M左右，请问这块有什么好建议么？（glide在9.0以下不支持动图webp）然后内存大是因为产生了很多WebPDecoder、FrameSeqDecoder、WebpDrawable等，这些缓存可以在比如页面关闭时手动清理么？

**Comment by penfeizhou** [comment]
本库的glide插件是依赖glide的管理机制的，如果手动关闭请参照glide的API以及本库的API。

**Comment by penfeizhou** [comment]
对于动图webp的支持情况,Android 9前后版本好像并无什么区别. 
我不清楚你的测试有没有控制变量,这个是否在同样的硬件情况下得出的结论.
 对于WebPDecoder存在于内存中无释放么,那是因为Glide本身的内存缓存缓存了这些对象,你可以选择调用glide的API关闭内存缓存.即使存在于内存中, 只要Glide 调用了Animatable的stop方法(Glide都自动对window区域外的进行调用), WebpDrawable就可以释放掉多余内存,停止渲染线程.
