### ISSUE TITLE
Create animated webp

### ISSUE THREAD

**Issue by didi789** [penfeizhou/APNG4Android#17]
Can I use this library to create animated webp (with alpha channel) from batch of bitmaps?
Or maybe from GIF?

**Comment by penfeizhou** [comment]
The library does not support this for now.

**Comment by didi789** [comment]
I'm looking for it for months, its the closet library I came to.
I see that there is webp decoder, and inside you enecode each chunk and chunk
So, I guess that the enecoding tool development isn't gonna be hard, I'm wrong?
https://github.com/b4rtaz/android-webp-encoder
This library works nice, but it doesn't support ALPHA channel, May you help me figure out how to implement the ALPHA channel in this library?

Thanks in advance,
Nirel.

**Comment by penfeizhou** [comment]
Hi nirel, I think it missed to deal with ALPH Chunk which is used to control the alpha channel in WebP.

**Comment by didi789** [comment]
I know, that's why I'm not using it. (Its on b4rtaz TODO for more than one year..)
That's why I'm asking if you can add it into your library, I'll be grateful

**Comment by penfeizhou** [comment]
OK, you can get the library `implementation 'com.github.penfeizhou.android.animation:awebpencoder:1.0.1'` in jcenter.
And use like this:
```java
 final byte[] ret = WebPEncoder.fromGif(new AssetStreamLoader(EncoderTestActivity.this,
                        "1.gif")).build();
```
or add a batch of bitmaps
```java
public WebPEncoder addFrame(FrameInfo frameInfo);
```

**Comment by didi789** [comment]
That's amazing! thank you so much!
I'm tring to save it using FileOutputStream like this - 
```
            //write the bytes in file
            FileOutputStream fos = new FileOutputStream(file);
            fos.write(ret);
            fos.flush();
            fos.close();
```
But when tring to open it, it doesn't reconized by the system as an **webp** image :/
Any ideas?

**Comment by penfeizhou** [comment]
Please provide more details,or a detailed demo

**Comment by didi789** [comment]
Of course,
I'm tring to make a (very) simple webP from 1 pixel png, attached
https://user-images.githubusercontent.com/14198588/62539667-6c9a5100-b85e-11e9-8ec9-1f1b3da78ff6.png

But I'm having a problem,
The result using the awebpencoder-
https://srv-file2.gofile.io/download/QfnGiM/1pixel.webp

The expected result-
https://srv-file2.gofile.io/download/m9HSt6/1pixelworks.webp

Even when I'm tring to use fromGif, for this gif for example - 
![example](https://user-images.githubusercontent.com/14198588/62540097-72dcfd00-b85f-11e9-932c-76c7660fec48.gif)

It doesn't works well

My code:
![image](https://user-images.githubusercontent.com/14198588/62540197-bafc1f80-b85f-11e9-821d-cb932942f012.png)

Thanks in advance,
Nirel.

**Comment by didi789** [comment]
@penfeizhou any ideas?

**Comment by MarsVard** [comment]
Did anybody get this to work?

**Comment by amitkle** [comment]
Looks so good, such a shame it doesn't work :(
