### ISSUE TITLE
我设置了aaptoptions 禁用了对于png的优化，此时我想放到Drawable文件夹下 使用ResourceStreamLoader不能正常展示

### ISSUE THREAD

**Issue by omyrobin** [penfeizhou/APNG4Android#170]
由于我们的apng图片是才用插件方式加载到宿主应用中的， apng被放到了插件apk的drawable文件夹中，然后通过反射并入宿主的Resource，我想使用ResourceStreamLoader 来加载 不能正确显示apng图片，我已经确认过 插件apk确实设置了aaptoptions 禁用了对于png的优化，插件apk中的文件可以使用apng预览工具正常预览，请问这种情况下ResourceStreamLoader依然不能正常加载apng吗

**Comment by penfeizhou** [comment]
能不能加载取决于读到的文件是不是完整的

**Comment by penfeizhou** [comment]
请确保打包等环节的文件完整性。
