### ISSUE TITLE
If I share the same APNGDrawable, I want to deal with it differently.

### ISSUE THREAD

**Issue by jeho1335** [penfeizhou/APNG4Android#172]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  |  Samsung Galaxy S22+                              |      |
| System Version               |  13.0                                             |      |
| APNG4Android Library Version |  2.23.0                                           |      |
| Repro rate                   | 100%   |      |

### Issue Description and Steps

If I share the same APNGDrawable, I want to deal with it differently.

I'm using the apng glide plugin together.

imageView.setImageDrawable inside the onResourceReady() callback of the glideCustomTarget.

In this case, if the same APNG resource URL is used, the same APNGDrawable is shared, so if apngDrawable.stop() is performed on a resource, the same resource elsewhere on the screen is also stopped.

To resolve this issue, inside the onResourceReday() callback
I tried using Drawable.mute() but it didn't work.

Probably because the FrameSeqDecoder inside the APNGDrawable is the same object.

How do I solve this problem?

**Comment by jingpeng** [comment]
Hi, if you use glide, you can configure different cache keys you can check this [GlideUrl](https://bumptech.github.io/glide/javadocs/410/com/bumptech/glide/load/model/GlideUrl.html) to solve the problem

**Comment by jeho1335** [comment]
@jingpeng Hi. First, thank for answer.

Yes. When i used a diffrent cache key, this issue is cleared.

But, diffrent cache key is a more use the app, the more cache space need (I use a skipMemoryCache(true) option in glide. because saving a memory space)

Is there any other solution?

**Comment by initialjie** [comment]
Yes, you can achieve that.

- Define a "isStop" boolean member in FrameAnimationDrawable.
- Set isStop to true when you stop your specific drawable, likely, set isStop to false when you start drawable again.
- Check whether isStop is true onRender callback, if it does, do nothing.
