### ISSUE TITLE
Min SDK version

### ISSUE THREAD

**Issue by stom79** [penfeizhou/APNG4Android#18]
Hey,
I wonder if the library could accept a lower minSdkVersion currently set to 19?

**Comment by penfeizhou** [comment]
Yes it can be set to a lower minSDKVersion.

**Comment by stom79** [comment]
Would it be possible for you to change this value? Your lib is an important part of my project now and that will help to have a lower value. Thanks!

**Comment by penfeizhou** [comment]
I'll change to API 16

**Comment by penfeizhou** [comment]
You can upgrade to version 1.0.1.

**Comment by stom79** [comment]
Thank you! :+1:
