### ISSUE TITLE
调用 setBounds 有问题

### ISSUE THREAD

**Issue by wangkunlin** [penfeizhou/APNG4Android#182]
logcat 一直输出：onRender:Buffer not large enough for pixels

**Comment by wangkunlin** [comment]
awebp

**Comment by jingpeng** [comment]
有具体的图片资源链接么

**Comment by wangkunlin** [comment]
[加载_90x90_iSpt.webp.zip](https://github.com/penfeizhou/APNG4Android/files/11283646/_90x90_iSpt.webp.zip)
这个图

**Comment by wangkunlin** [comment]
如果我不调用 setBounds 是可以播的，但是我想给他缩小，然后我设置了 setBounds(0,0,10,10) ，结果就不播了，log 里一直输出 onRender:Buffer not large enough for pixels

**Comment by jingpeng** [comment]
setBounds不可以随便调用，这个关乎画布中像素多少，如果需要绘制的bitmap大于画布buffer大小，则不会绘制

**Comment by wangkunlin** [comment]
我大概看了一下 setBounds 的实现，貌似是有缩放的逻辑，好像读取帧数据时进行了缩放，但创建的 bitmap 没有大小没有缩放
