### ISSUE TITLE
异常报错

### ISSUE THREAD

**Issue by ThinkAgains** [penfeizhou/APNG4Android#185]
#[](url)
![微信截图_20230428173546](https://user-images.githubusercontent.com/18339201/235113413-c3115bd8-53ea-4202-add9-c83fad26b047.png)

**Comment by ThinkAgains** [comment]
使用方式：Glide.with(imageView.context).load(url).into(imageView)

**Comment by penfeizhou** [comment]
请给出可复现问题的Demo代码
