### ISSUE TITLE
使用Glide插件 加载没有动画效果了？

### ISSUE THREAD

**Issue by skyofsky** [penfeizhou/APNG4Android#186]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

 kotlin语言

 1.Glide.with(this).load("https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp")
                    .into(it)
  2. Glide.with(this).load("https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp")
                    .into(object : CustomTarget<Drawable>() {
                        override fun onResourceReady(
                            resource: Drawable,
                            transition: Transition<in Drawable>?
                        ) {
                            LogUtils.e("resource.javaClass.name=${resource.javaClass.name} ${resource.intrinsicWidth}")
                            if(resource is WebPDrawable){
                                binding?.enterRoomWebp?.setImageDrawable((resource as WebPDrawable))
                            }
                        }

                        override fun onLoadCleared(placeholder: Drawable?) {

                        }

                    })
resource.javaClass.name=com.github.penfeizhou.animation.webp.WebPDrawable

**Comment by penfeizhou** [comment]
If you use customTarget, please start `WebPDrawable ` manually

``` java
webPDrawable.start()

```
