### ISSUE TITLE
How to load APNG file from Shared AssetFolder.?

### ISSUE THREAD

**Issue by Arun1947** [penfeizhou/APNG4Android#187]
How can we load ANPG files from a folder inside the AssetFolder.?

For eg :- I want to load from a folder named "apng"
assests -> apng -> (loader.png)->APNG file

**Comment by penfeizhou** [comment]
Just use AssetStreamLoader
```java
// Load from asset file
AssetStreamLoader assetLoader = new AssetStreamLoader(context, "apng/wheel.png");

// Create APNG Drawable
APNGDrawable apngDrawable = new APNGDrawable(assetLoader);
```

**Comment by Arun1947** [comment]
[penfeizhou](https://github.com/penfeizhou) 
It worked fine.
Thanks for your reply..!
