### ISSUE TITLE
Glide support

### ISSUE THREAD

**Issue by stom79** [penfeizhou/APNG4Android#19]
Does the Glide support change the general behaviour (or is it a change in Glide 4.9.0)? I will explain my issue.

I was using Glide in that way for loading some profile pictures:

```
 Glide.with(imageView.getContext())
                        .load(url)
                        .apply(new RequestOptions().transforms(new CenterCrop(), new RoundedCorners(10)))
                        .into(imageView);
```
When it was a gif URL, that worked but now I get a message telling me it can't load a gif image as a bitmap.

My current fix is:

```
 if ( url.endsWith(".gif")) {
            try {
                Glide.with(imageView.getContext())
                        .asGif()
                        .load(url)
                        .apply(new RequestOptions().transforms(new CenterCrop(), new RoundedCorners(10)))
                        .into(imageView);
            } catch (Exception ignored) {
            }
        } else {
            try {
                Glide.with(context)
                        .asBitmap()
                        .apply(new RequestOptions().transforms(new CenterCrop(), new RoundedCorners(10)))
                        .load(urlStatic)
                        .into(imageView);
            } catch (Exception ignored) {
            }
        }
```

**Comment by penfeizhou** [comment]
It default use my gif decoder which is implemented by C++ with better performance instead of the glide's version of gif decoder.
So please don't use `asGif`,this translates to glide's gifdrawable.
Just use `asDrawable()` is ok.
If you want to use gilde's decoder,you can disable my gif decoder,
Though I don't recommend you to do that:
```java
GlideApp.with(imageView)
                    .load(url)
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, true)
                    .into(imageView);
```

**Comment by stom79** [comment]
Oh OK! Good to know that. I will change my code in this way. Thanks for the tip.

**Comment by penfeizhou** [comment]
```
                .apply(new RequestOptions().transforms(new CenterCrop(), new RoundedCorners(10)))
```
The problem is here.
Custom drawables  does not support glide transforms.
I suggest you do corner use CardView.And set scale type for the imageview instead of using glide transforms.
