### ISSUE TITLE
Cause: broken jar file?: com.github.penfeizhou.animation.frameanimation.R

### ISSUE THREAD

**Issue by Hung2299** [penfeizhou/APNG4Android#208]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue when build project and can't run app
i can't implement v2.28.0 . i am using v2.25.0

Cause: broken jar file?: com.github.penfeizhou.animation.frameanimation.R

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.
<img width="660" alt="image" src="https://github.com/penfeizhou/APNG4Android/assets/86958584/094568f8-7b0c-468d-aba3-005cde8be07a">

**Comment by jingpeng** [comment]
perhaps your local gradle cache is broken
