### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError android.graphics.Bitmap.nativeCreate (Bitmap.java)  android.graphics.Bitmap.createBitmap (Bitmap.java:991)

### ISSUE THREAD

**Issue by cxqq123** [penfeizhou/APNG4Android#215]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info
Fatal Exception: java.lang.OutOfMemoryError
android.graphics.Bitmap.nativeCreate (Bitmap.java)

android.graphics.Bitmap.createBitmap (Bitmap.java:991)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.createBitmap (FrameSeqDecoder.java:991)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.getShareBitmap (FrameSeqDecoder.java:974)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.copyPixelBufferToShareBitmap (FrameSeqDecoder.java:837)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.access$600 (FrameSeqDecoder.java)
com.github.penfeizhou.animation.decode.FrameSeqDecoder$3.run (FrameSeqDecoder.java:174)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.innerStart (FrameSeqDecoder.java:504)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.lambda$new$1 (FrameSeqDecoder.java)
android.os.Handler.handleCallback (Handler.java:883)

android.os.HandlerThread.run (HandlerThread.java:67)

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by penfeizhou** [comment]
please give more information before reopened.
