### ISSUE TITLE
AVIF module is unavailable on maven

### ISSUE THREAD

**Issue by RobbWatershed** [penfeizhou/APNG4Android#216]
Got this error when trying to fetch the latest version using Gradle : `Failed to resolve: com.github.penfeizhou.android.animation:avif:3.0.0`

When [browsing maven](https://mvnrepository.com/artifact/com.github.penfeizhou.android.animation), the module isn't there.

**Comment by penfeizhou** [comment]
I've fixed this. Please retry on Release 3.0.1
