### ISSUE TITLE
你好大神，内存问题

### ISSUE THREAD

**Issue by stewForAni** [penfeizhou/APNG4Android#24]
1.很感谢你的库。
2.使用FileLoader加载apng文件，出现内存以0.2M/s的速度在增加，然后加载到一定大小又回回到原内存，请问这种情况是什么原因？是否正常？

**Comment by penfeizhou** [comment]
谢谢。
可以贴图看一下。
播放开始阶段内存的增加是少量且必须的。但动画播放过程中是无额外内存增加，保持稳定的。
