### ISSUE TITLE
调用stop方法会ANR

### ISSUE THREAD

**Issue by StevenYan88** [penfeizhou/APNG4Android#28]

**Comment by penfeizhou** [comment]
你好，能请提供详细的复现路径或线程堆栈吗

**Comment by StevenYan88** [comment]
见附件 谢谢！


------------------ 原始邮件 ------------------
发件人: "osborn"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 中午11:30
收件人: "penfeizhou/APNG4Android"<APNG4Android@noreply.github.com>;
抄送: "1059408192"<1059408192@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [penfeizhou/APNG4Android] 调用stop方法会ANR (#28)




你好，能请提供详细的复现路径或线程堆栈吗
