### ISSUE TITLE
加载大量的WebP有问题，你这是本地的。

### ISSUE THREAD

**Issue by 183883324** [penfeizhou/APNG4Android#34]
如抖音那样 加载大量的webp  图片大小容易跳动  图片 大小无法固定
![image](https://user-images.githubusercontent.com/37425595/64404986-4c092500-d0b0-11e9-9e01-082de0909f3b.png)

**Comment by 183883324** [comment]
能加你QQ问下这个问题嘛？

**Comment by penfeizhou** [comment]
291548784
