### ISSUE TITLE
【Crash】APNGParser$FormatException: APNG Format error

### ISSUE THREAD

**Issue by SherlockGougou** [penfeizhou/APNG4Android#38]
线上出现大量：
```
Caused by: com.github.penfeizhou.animation.apng.decode.APNGParser$FormatException: APNG Format error
    at com.github.penfeizhou.animation.apng.decode.APNGParser.parse(APNGParser.java)
    at com.github.penfeizhou.animation.apng.decode.APNGDecoder.read(APNGDecoder.java)
    at com.github.penfeizhou.animation.apng.decode.APNGDecoder.read(APNGDecoder.java)
    at com.github.penfeizhou.animation.decode.FrameSeqDecoder$2.call(FrameSeqDecoder.java)
    at com.github.penfeizhou.animation.decode.FrameSeqDecoder$2.call(FrameSeqDecoder.java)
```
Android版本均有分布，机型也均有分布。
我是使用OKhttp下载到本地后，使用此框架加载的。

**Comment by jingpeng** [comment]
你加载的图片是apng吗

**Comment by SherlockGougou** [comment]
是的，仅仅更改了文件的后缀为：.apng，是为了好区分。也通过浏览器打开试过，能动态显示。

**Comment by SherlockGougou** [comment]
这些是cdn配置的图片信息：
'''
{"updateTime":1569673535,"startTime":1569772800,"endTime":1570464000,"images":{"home":{"androidPng":"https://aloss.duoke678.com/app/img/tabbar/android/png/home.png","apng":"https://aloss.duoke678.com/app/img/tabbar/ios/apng/home.apng","androidApng":"https://aloss.duoke678.com/app/img/tabbar/android/apng/home.apng"},"find":{"androidPng":"https://aloss.duoke678.com/app/img/tabbar/android/png/find.png","apng":"https://aloss.duoke678.com/app/img/tabbar/ios/apng/find.apng","androidApng":"https://aloss.duoke678.com/app/img/tabbar/android/apng/find.apng"},"hot":{"androidPng":"https://aloss.duoke678.com/app/img/tabbar/android/png/hot.png","apng":"https://aloss.duoke678.com/app/img/tabbar/ios/apng/hot.apng","androidApng":"https://aloss.duoke678.com/app/img/tabbar/android/apng/hot.apng"},"me":{"androidPng":"https://aloss.duoke678.com/app/img/tabbar/android/png/me.png","apng":"https://aloss.duoke678.com/app/img/tabbar/ios/apng/me.apng","androidApng":"https://aloss.duoke678.com/app/img/tabbar/android/apng/me.apng"}}}

'''

**Comment by penfeizhou** [comment]
你好，您可以通过APNGParser.isAPNG 方法提前校验图片是否apng格式。
从crash日志看是文件格式错误，请您确认已完整下载了图片内容后再加载的。此类应用问题请提供可复现该问题的demo。感谢您的支持，谢谢

**Comment by jingpeng** [comment]
如果不是apng文件，改后缀是不行的

**Comment by SherlockGougou** [comment]
我上面发的所有的.apng的图片，都经过浏览器打开测试过，能正常动态显示。是否是存在机型兼容性问题？

**Comment by penfeizhou** [comment]
这个格式错误与机型没有关系，请看下载的图片内容

**Comment by SherlockGougou** [comment]
好的，我使用之前校验一下格式。
