### ISSUE TITLE
Rendering webP image wrong.

### ISSUE THREAD

**Issue by rivalnhwc** [penfeizhou/APNG4Android#39]
hi,
   I'm using APNG4Android source code with Glide, when testing ,apng and gif get nothing wrong, but webP seems to have some rendering problem.
- When some webP image playing, i can see white rectangle area with some colorful pixels on it. Seems like something wrong with blending.
 - And some other webP image playing faster than the speed it playing on webpage.
 >  Hope you can help me! Thanks.
- webP image with white rect url:
https://misc.aotu.io/ONE-SUNDAY/world_cup_2014_42.webp
https://misc.aotu.io/ONE-SUNDAY/BladeRunner.webp
- webP image running fast url:
https://misc.aotu.io/ONE-SUNDAY/SteamEngine.webp
https://misc.aotu.io/ONE-SUNDAY/SteamEngine_lossy.webp

**Comment by jingpeng** [comment]
Hello, can you provide your device info & detailed code?

**Comment by rivalnhwc** [comment]
Google nexus6 
Android 7.1.1
```
GlideApp.with(mContext)
                .load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.webp")
                .into(imageView);

```

I just tried some other phone, they don't have the white rect question, but for that too webP image, still running faster.

**Comment by rivalnhwc** [comment]
I print frame.frameDuration in FrameSeqDecoder.step()
> https://misc.aotu.io/ONE-SUNDAY/SteamEngine.webp
> https://misc.aotu.io/ONE-SUNDAY/SteamEngine_lossy.webp
this two images which running faster shows 0, maybe that is the problem, but it was the image itself has problem or the parser?

**Comment by sun55** [comment]
能不能加载网络webp资源，加载本地的webp资源时透明部分会变为白色

**Comment by penfeizhou** [comment]
> 能不能加载网络webp资源，加载本地的webp资源时透明部分会变为白色

Please move to a new issue

**Comment by penfeizhou** [comment]
> I print frame.frameDuration in FrameSeqDecoder.step()
> 
> > https://misc.aotu.io/ONE-SUNDAY/SteamEngine.webp
> > https://misc.aotu.io/ONE-SUNDAY/SteamEngine_lossy.webp
> > this two images which running faster shows 0, maybe that is the problem, but it was the image itself has problem or the parser?

 /**
     * Frame Duration: 24 bits (uint24)
     * The time to wait before displaying the next frame, in 1 millisecond units.
     * Note the interpretation of frame duration of 0 (and often <= 10) is implementation defined.
     * Many tools and browsers assign a minimum duration similar to GIF.
     */
    int frameDuration;

**Comment by penfeizhou** [comment]
In later version of this librrary,we will set a default value 100ms when the frame duration is 0.

**Comment by penfeizhou** [comment]
We will fix this and set frame duration's default value to 100 when it's value is 0 from origin file as how chrome deals with it.

**Comment by sun55** [comment]
OK, really appreciate your help!



 
  
  
  
  


 




------------------ 原始邮件 ------------------
发件人: "osborn"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 下午4:05
收件人: "penfeizhou/APNG4Android"<APNG4Android@noreply.github.com>;
抄送: "sun"<670736533@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [penfeizhou/APNG4Android] Rendering webP image wrong. (#39)




We will fix this and set frame duration's default value to 100 when it's value is 0 from origin file as how chrome deals with it.

**Comment by sun55** [comment]
> Google nexus6
> Android 7.1.1
> 
> ```
> GlideApp.with(mContext)
>                 .load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.webp")
>                 .into(imageView);
> ```
> 
> I just tried some other phone, they don't have the white rect question, but for that too webP image, still running faster.

GlideApp是怎么引用的，我想加载远程apng或者webp格式资源，还需要判断动画播放的开始和结束状态
