### ISSUE TITLE
能不能加载网络webp资源，加载本地的webp资源时透明部分会变为白色

### ISSUE THREAD

**Issue by penfeizhou** [penfeizhou/APNG4Android#42]
能不能加载网络webp资源，加载本地的webp资源时透明部分会变为白色

_Originally posted by @sun55 in https://github.com/penfeizhou/APNG4Android/issues/39#issuecomment-547772153_

**Comment by penfeizhou** [comment]
可以使用Glide加载网络图片
```gradle
repositories {
    maven {
        url "https://dl.bintray.com/osborn/Android"
    }
}
dependencies {
    implementation 'com.github.penfeizhou.android.animation:glide-plugin:1.1.0'
}
```
```java
Glide.with(imageView).load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png").into(imageView);
```

另透明变白色的问题请浏览器打开看是否是文件问题

**Comment by sun55** [comment]
Glide.with(imageView).load("https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp").into(imageView);
使用上述代码加载webp动画文件，显示结果为静态图片，
把webp文件放在项目中加载，显示透明区域为白色，浏览器显示正常

 
  
  
  
  


 




------------------ 原始邮件 ------------------
发件人: "osborn"<notifications@github.com>;
发送时间: 2019年10月30日(星期三) 下午3:58
收件人: "penfeizhou/APNG4Android"<APNG4Android@noreply.github.com>;
抄送: "sun"<670736533@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [penfeizhou/APNG4Android] 能不能加载网络webp资源，加载本地的webp资源时透明部分会变为白色 (#42)




可以使用Glide加载网络图片
 repositories {     maven {         url "https://dl.bintray.com/osborn/Android"     } } dependencies {     implementation 'com.github.penfeizhou.android.animation:glide-plugin:1.1.0' }
 Glide.with(imageView).load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png").into(imageView);
 
另透明变白色的问题请浏览器打开看是否是文件问题

**Comment by penfeizhou** [comment]
请直接看demo中测试代码，
这个页面的底色是白色，你改成其他颜色看看
In activity_apnglib.xnl
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#00ff00"
....
```

**Comment by sun55** [comment]
还是有白底问题，然后我想加载网络webp资源，并且能监听到动画播放状态，
GlideApp.with(imageView)
        .load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.webp")
        .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, false)
        .into(imageView);
上面的GlideApp是否可以实现，需要添加哪些依赖可以使用它，谢谢


&nbsp;

&nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "osborn"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 下午5:26
收件人: "penfeizhou/APNG4Android"<APNG4Android@noreply.github.com&gt;; 
抄送: "sun"<670736533@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [penfeizhou/APNG4Android] 能不能加载网络webp资源，加载本地的webp资源时透明部分会变为白色 (#42)




请直接看demo中测试代码，
 这个页面的底色是白色，你改成其他颜色看看
 In activity_apnglib.xnl
 <?xml version="1.0" encoding="utf-8"?&gt; <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"     android:layout_width="match_parent"     android:layout_height="match_parent"     android:background="#00ff00" ....
