### ISSUE TITLE
Glide加载WebP会出现ANR

### ISSUE THREAD

**Issue by 183883324** [penfeizhou/APNG4Android#46]

**Comment by jingpeng** [comment]
请不要所有cell加载同一张图，否则会出现ANR，如果一定要加载同一张，请在url后面跟随时间戳

**Comment by 183883324** [comment]
不太清楚你表达什么意思，能不能给的deno!



---原始邮件---
发件人: "jingpeng"<notifications@github.com&gt;
发送时间: 2019年11月13日(星期三) 下午3:01
收件人: "penfeizhou/APNG4Android"<APNG4Android@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"朽木自雕"<183883324@qq.com&gt;;
主题: Re: [penfeizhou/APNG4Android] Glide加载WebP会出现ANR (#46)



请不要所有cell加载同一张图，否则会出现ANR，如果一定要加载同一张，请在url后面跟随时间戳

**Comment by jingpeng** [comment]
麻烦详细看demo工程，https://github.com/penfeizhou/APNG4Android/blob/master/app/src/main/java/com/github/penfeizhou/animation/demo/TestAdapter.java

**Comment by 183883324** [comment]
好的，非常感谢。



---原始邮件---
发件人: "jingpeng"<notifications@github.com&gt;
发送时间: 2019年11月13日(星期三) 晚上6:42
收件人: "penfeizhou/APNG4Android"<APNG4Android@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"朽木自雕"<183883324@qq.com&gt;;
主题: Re: [penfeizhou/APNG4Android] Glide加载WebP会出现ANR (#46)



麻烦详细看demo工程，https://github.com/penfeizhou/APNG4Android/blob/master/app/src/main/java/com/github/penfeizhou/animation/demo/TestAdapter.java
