### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by ZeroCandy** [penfeizhou/APNG4Android#50]
`12-04 20:48:21.560 E/AndroidRuntime(10899): FATAL EXCEPTION: FrameDecoderExecutor-1
12-04 20:48:21.560 E/AndroidRuntime(10899): Process: com.xxx.xxx, PID: 10899
12-04 20:48:21.560 E/AndroidRuntime(10899): java.lang.IllegalStateException: copyPixelsFromBuffer called on recycled bitmap
12-04 20:48:21.560 E/AndroidRuntime(10899): at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
12-04 20:48:21.560 E/AndroidRuntime(10899): at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:549)
12-04 20:48:21.560 E/AndroidRuntime(10899): at com.github.penfeizhou.animation.FrameAnimationDrawable.onRender(FrameAnimationDrawable.java:11)
12-04 20:48:21.560 E/AndroidRuntime(10899): at com.github.penfeizhou.animation.decode.FrameSeqDecoder$1.run(FrameSeqDecoder.java:7)
12-04 20:48:21.560 E/AndroidRuntime(10899): at android.os.Handler.handleCallback(Handler.java:751)
12-04 20:48:21.560 E/AndroidRuntime(10899): at android.os.Handler.dispatchMessage(Handler.java:95)
12-04 20:48:21.560 E/AndroidRuntime(10899): at android.os.Looper.loop(Looper.java:154)
12-04 20:48:21.560 E/AndroidRuntime(10899): at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by ZeroCandy** [comment]
加载APNG的时候出现

**Comment by penfeizhou** [comment]
版本号是什么？能否提供下能出现这个问题的PNG图片

**Comment by ZeroCandy** [comment]
> 版本号是什么？能否提供下能出现这个问题的PNG图片

`implementation 'com.github.penfeizhou.android.animation:glide-plugin:1.3.1'

不是特定的APNG图片导致的崩溃，而是使用ViewPager切换Fragment，Fragment是一个APNG图片列表，在切换的过程中偶尔会出现的异常。
