### ISSUE TITLE
How does it happen？ Buffer not large enough for pixels

### ISSUE THREAD

**Issue by nervending** [penfeizhou/APNG4Android#55]
### How does it happen？
我看了一下最近1.3.3 change log，增加了一条 Avoid buffer size smaller than the target bitmap。
想确认一下这个是在什么情况下出现的，因为修复的代码只是做了一个防止错误的出现而已，是否彻底解决了问题？

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  |  VIVO V3                               |      |
| System Version               | Android 5.1.1,level 22                                              |      |
| APNG4Android Library Version |   1.3.2                                           |      |
| Repro rate                   |   Per thousand   |      |
| Repro with our demo project  | no           |      |
| Demo project link            | e.g. link to a demo project that highlights the issue |      |

**Comment by penfeizhou** [comment]
It's only a protection for what may happend.That the allocated buffer size is not match what exactlly needed.

**Comment by ffts** [comment]
这边遇到了一种情况
有时FrameAnimationDrawable的onRender方法调用时frameSeqDecoder.getSampleSize()返回的是1
接着frameSeqDecoder的setDesiredSize调用，然后sampleSize就变成2了
再往后的onRender方法里，给过来的byteBuffer就小了，但是bitmap已经创建了，还是原来的大小所以
if (byteBuffer.remaining() < this.bitmap.getByteCount()) {
            Log.e(TAG, "onRender:Buffer not large enough for pixels");
            return;
        }
这个条件就一直是true了，就一直报这个错误了

**Comment by jingpeng** [comment]
你这个问题是在渲染过程中修改imageview的尺寸了吗

**Comment by ffts** [comment]
> 你这个问题是在渲染过程中修改imageview的尺寸了吗

我看开了个新issue，在那里说吧
