### ISSUE TITLE
DISABLE_ANIMATION_GIF_DECODER默认值问题

### ISSUE THREAD

**Issue by lingyun1120** [penfeizhou/APNG4Android#61]
`public static final Option<Boolean> DISABLE_ANIMATION_GIF_DECODER = Option.memory(           "com.github.penfeizhou.animation.glide.AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER", false);`
注释里面默认值是true，但是代码里面是false
现在使用glide加载图片，得到的GifDrawable是这个库的，不是glide默认的。

**Comment by penfeizhou** [comment]
是的，现在默认是false的，请问使用有问题吗？
