### ISSUE TITLE
Problem decoding into existing bitmap

### ISSUE THREAD

**Issue by qienanxiang** [penfeizhou/APNG4Android#63]
EXCEPTION LOG:
 java.lang.IllegalArgumentException: Problem decoding into existing bitmap
        at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:670)
        at com.github.penfeizhou.animation.webp.decode.AnimationFrame.draw(AnimationFrame.java:82)

**Comment by jingpeng** [comment]
nativeDecodeByteArray error from Android framework, you need to check whether your file is correct in format

**Comment by qienanxiang** [comment]
> nativeDecodeByteArray error from Android framework, you need to check whether your file is correct in format

thanks ! it works

**Comment by CrackerKSR** [comment]
Can you share the code snippet of decoding awebp?
