### ISSUE TITLE
WebPEncoder doesn't work

### ISSUE THREAD

**Issue by amitkle** [penfeizhou/APNG4Android#68]
Hello!
I saw your library and I really like it.
It is the only library I found that handles animated webp, but unfortunately I couldn't make it work.

I tried both:

final byte[] ret = WebPEncoder.fromGif(new AssetStreamLoader(context, "test.gif")).build();
File file = new File(context.getCacheDir(), "test.webp");
FileOutputStream fos = null;
try {
    fos = new FileOutputStream(file);
    fos.write(ret);
    fos.flush();
    fos.close();
} catch (Exception e) {
     e.printStackTrace();
}

and 

WebPEncoder encoder = new WebPEncoder();

int duration = 0;
for (int i = 0; i < standardGifDecoder.getFrameCount(); i++) {
    Bitmap bitmap = standardGifDecoder.getNextFrame();
    encoder.addFrame(bitmap, 0,0, standardGifDecoder.getNextDelay());
}

But both gave me an invalid webp file (attaching it).
[test1.zip](https://github.com/penfeizhou/APNG4Android/files/4977599/test1.zip)

The original gif:
![test](https://user-images.githubusercontent.com/15522474/88479297-a6280880-cf56-11ea-93f7-58db04b81bc6.gif)

It would be amazing if you could help me, or even direct me to the bug so I can open a PR.
Thanks!

**Comment by jingpeng** [comment]
ok, I will try and find whether exists a bug

**Comment by amitkle** [comment]
@jingpeng thank you! Very glad to hear :)

**Comment by NiaNingXue** [comment]
same issue.

**Comment by penfeizhou** [comment]
Lately we fixed the issue in version 2.3.0.You can try this now.

**Comment by amitkle** [comment]
@penfeizhou amazing!! Are you sure you uploaded the version? I can't find :/

**Comment by penfeizhou** [comment]
@amitkle please try again.

**Comment by NiaNingXue** [comment]
nice,  thank you

**Comment by NiaNingXue** [comment]
Recently I have study the protocol of Webp，it really had me going

**Comment by amitkle** [comment]
Found it, thank you very much :)

**Comment by amitkle** [comment]
@penfeizhou  @jingpeng 
Hey,
I tested this again and saw that the frames came on top of each other.

added the webp in the zip:
[animated_sticker.zip](https://github.com/penfeizhou/APNG4Android/files/5385001/animated_sticker.zip)

**Comment by jingpeng** [comment]
> @penfeizhou @jingpeng
> Hey,
> I tested this again and saw that the frames came on top of each other.
> 
> added the webp in the zip:
> [animated_sticker.zip](https://github.com/penfeizhou/APNG4Android/files/5385001/animated_sticker.zip)



> @penfeizhou @jingpeng
> Hey,
> I tested this again and saw that the frames came on top of each other.
> 
> added the webp in the zip:
> [animated_sticker.zip](https://github.com/penfeizhou/APNG4Android/files/5385001/animated_sticker.zip)

Do you have the original gif?

**Comment by amitkle** [comment]
> > @penfeizhou @jingpeng
> > Hey,
> > I tested this again and saw that the frames came on top of each other.
> > added the webp in the zip:
> > [animated_sticker.zip](https://github.com/penfeizhou/APNG4Android/files/5385001/animated_sticker.zip)
> 
> > @penfeizhou @jingpeng
> > Hey,
> > I tested this again and saw that the frames came on top of each other.
> > added the webp in the zip:
> > [animated_sticker.zip](https://github.com/penfeizhou/APNG4Android/files/5385001/animated_sticker.zip)
> 
> Do you have the original gif?

@jingpeng 
Thank you for the fast reply!
I couldn't find the original, but here are two others (orig gif, and it's converted webp)

[animated.zip](https://github.com/penfeizhou/APNG4Android/files/5390545/animated.zip)

**Comment by amitkle** [comment]
Is there any chance you've solved the problem?
@jingpeng @penfeizhou 
Thanks again!

**Comment by im-rifat** [comment]
@amitkle , assign "true" value to variable "blending" of frameinfo class. "frames came on top of each other" issue will be solved.

**Comment by CrackerKSR** [comment]
If I use above 2nd code snippet then How would I save the file .

``java
WebPEncoder encoder = new WebPEncoder();

int duration = 0;
for (int i = 0; i < standardGifDecoder.getFrameCount(); i++) {
Bitmap bitmap = standardGifDecoder.getNextFrame();
encoder.addFrame(bitmap, 0,0, standardGifDecoder.getNextDelay());
```

I tried encoder.build() after adding frame and stored the returned byte[] into file which gave incorrect file. It seems I did wrong.
