### ISSUE TITLE
Loading APNG with Glide plugin - not working

### ISSUE THREAD

**Issue by johnaziz57** [penfeizhou/APNG4Android#69]
### Issue Info
Loading APNG doesn't show an animated image.

Trying to load APNG into an ImageView using the following code

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        Glide
            .with(this)
            .load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png")
            .into(img)
    }
}
```

With the following dependencies

   ```
 implementation 'com.github.bumptech.glide:glide:4.11.0'
 annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'
 implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.0.0'
```

Image is loaded but it is not moving, I tried the one with WebP `https://isparta.github.io/compare-webp/image/gif_webp/webp/2.webp` and it is working perfectly.

Device tested on:
Emulator: Nexus 5 API 28
minSdkVersion: 26
targetSdkVersion: 30

Also used this Image, still same result
![chilled_koala](https://user-images.githubusercontent.com/14923445/90147090-17065780-dd82-11ea-9693-52edf51a0021.png)

I would be happy to support more info

Any idea why is this happening?

**Comment by jingpeng** [comment]
make sure to use 
implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.0.0'
with glide 4.8.0

**Comment by johnaziz57** [comment]
@jingpeng I noticed that I have list the dependencies incorrectly.
I have updated my post

I have also tested with 4.8.0, still giving me a static image

I have uploaded my code into a repo
https://github.com/johnaziz57/APNG4Android_Glide_APNG_Bug

**Comment by jingpeng** [comment]
You can try with GlideApp
GlideApp.with(imageView)
                    .load(url)
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, false)
                    .into(imageView);

**Comment by johnaziz57** [comment]
@jingpeng , I've just tested, same results, static image

**Comment by penfeizhou** [comment]
Please add GlideModule Class in your project.
```java
package com.example.glide_apng;

import com.bumptech.glide.annotation.GlideModule;
import com.bumptech.glide.module.AppGlideModule;

@GlideModule
public class MyGlideModule extends AppGlideModule {
}

```
You can use glide 4.11.0 since you've already used androidx

**Comment by penfeizhou** [comment]
> @jingpeng I noticed that I have list the dependencies incorrectly. I apologise for that.
> I have updated my post accordingly
> 
> I have also tested with 4.8.0, still giving me a static image
> 
> I have uploaded my code into a repo
> https://github.com/johnaziz57/APNG4Android_Glide_APNG_Bug
@johnaziz57 
It worked in this project.
1· Change to glide 4.11.0
2.Add `MyGlideModule`. That's why the glide plugin doesn't work.

**Comment by johnaziz57** [comment]
@penfeizhou @jingpeng, You guys are right. tested it with `GlideApp` and it is working
Thanks , and also a lot guys for your fast response.
