### ISSUE TITLE
FrameAnimationDrawable onRender

### ISSUE THREAD

**Issue by penfeizhou** [penfeizhou/APNG4Android#70]
这边遇到了一种情况
有时FrameAnimationDrawable的onRender方法调用时frameSeqDecoder.getSampleSize()返回的是1
接着frameSeqDecoder的setDesiredSize调用，然后sampleSize就变成2了
再往后的onRender方法里，给过来的byteBuffer就小了，但是bitmap已经创建了，还是原来的大小所以
if (byteBuffer.remaining() < this.bitmap.getByteCount()) {
            Log.e(TAG, "onRender:Buffer not large enough for pixels");
            return;
        }
这个条件就一直是true了，就一直报这个错误了

_Originally posted by @ffts in https://github.com/penfeizhou/APNG4Android/issues/55#issuecomment-676038317_

**Comment by ffts** [comment]
@jingpeng 
没有修改imageview的尺寸，是一个固定的尺寸的
不过和glide一起用的
场景上是在第一个页面展示了一张apng，然后到了下个页面在另一个尺寸比较小的imageview上展示的时候会出现这个问题
我看到有提到相同的地址用asFile的方式，我试试这种方法

**Comment by jingpeng** [comment]
这个情况会引发Glide复用Drawable，掉落到相同FrameSeqDecoder内，造成状态错乱，这种情况下需要手动区分出相同链接，最好是相同链接复用时url上跟时间参数，比如http://xxx.png?timestamp=xxx来防止此类问题发生

**Comment by ffts** [comment]
试了一下貌似不是复用的问题
应该是ImageView的scaleType设置成了fitXY才产生的问题
现在看应该是FrameAnimationDrawable的onRender最开始会比frameSeqDecoder的setDesiredSize先调用
frameSeqDecoder.getSampleSize()默认是1，不设置scaleType的时候，貌似setDesiredSize之后也是1，但是设置了scaleType=fitXY的话，ImageView比较小的时候在setDesiredSize调用之后就会变，但是FrameAnimationDrawable里的bitmap已经创建了

我在dome里试了下可以重现
<ImageView
            android:id="@+id/image"
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:scaleType="fitXY"/>
imageview是这样的
在onCreate里这样调用
imageView = findViewById(R.id.image);
        GlideApp.with(imageView)
                .load("https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png")
                .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, false)
                .into(imageView);
就会出现问题
![device-2020-08-20-143646](https://user-images.githubusercontent.com/1276568/90726040-a74d1b00-e2f3-11ea-9fa1-d9fb725deb91.png)
不设置scaleType的是没事的
![device-2020-08-20-143818](https://user-images.githubusercontent.com/1276568/90726055-afa55600-e2f3-11ea-87d7-0f7df42bc5c7.png)

**Comment by jingpeng** [comment]
好的我debug下

**Comment by jingpeng** [comment]
最新的master的代码修复了此问题
