### ISSUE TITLE
ConcurrentModificationException in v2.2.0

### ISSUE THREAD

**Issue by VeerHan** [penfeizhou/APNG4Android#77]
###################### APP CRASHED ######################
*********************************************************
Crash Time         : 2020-09-29 12:27:08
Device Manufacturer: Xiaomi
Device Model       : Redmi K30 Pro
Android Version    : 10
Android SDK        : 29
App VersionName    : 1.0.3
App VersionCode    : 23
*********************************************************
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at com.github.penfeizhou.animation.FrameAnimationDrawable$1.handleMessage(FrameAnimationDrawable.java:51)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by penfeizhou** [comment]
> Hi @penfeizhou.
> 
> This issue still reproducable in 2.21.0 (and it seems it was never fixed because @VeerHan closed it).
> 
> ```
> java.util.ConcurrentModificationException
>     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
>     at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
>     at com.github.penfeizhou.animation.FrameAnimationDrawable$1.handleMessage(FrameAnimationDrawable.java:59)
>     at android.os.Handler.dispatchMessage(Handler.java:106)
>     at android.os.Looper.loopOnce(Looper.java:201)
>     at android.os.Looper.loop(Looper.java:288)
>     at android.app.ActivityThread.main(ActivityThread.java:7870)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> ```
> 
> It happens to us when we're trying modify callbacks within registered callback. For example, if we want to register a one shot "on end" callback that unsubscribes right after callback invokation.
> 
> ```
> drawable.registerAnimationCallback(object : AnimationCallback() {
>     override fun onAnimationEnd(d: Drawable) {
>         // Do something useful, then unregister to stop receiving events.
>         drawable.unregisterAnimationCallback(this)
>     }
> }) 
> ```
> 
> I believe this is a valid use-case if we don't want to receive any more callbacks. If you check Android's `AnimatedVectorDrawable` implementation you will notice that they're making a defensive copy of callbacks before calling them. Maybe you can do the same.
> 
> I guess you can reproduce such crash with this sample:
> 
> ```
> val drawable = // instantiate any of FrameAnimationDrawable implementations
> drawable.registerAnimationCallback(object : AnimationCallback() {
>     override fun onAnimationStart(d: Drawable) {
>         // Unregister to modify underlying collection.
>         drawable.unregisterAnimationCallback(this)
>     }
> }) 
> drawable.registerAnimationCallback(object : AnimationCallback() {
>     // Just an empty callback to simulate multiple callbacks in the collection.
>     // It should be registered as the last one to make sure iterator has the next element.
> })
> drawable.start()
> ```

Thanks for your advice. This is fixed in v2.23.0
