### ISSUE TITLE
相邻的两个页面加载同一张apng图

### ISSUE THREAD

**Issue by mafanwei** [penfeizhou/APNG4Android#82]
### New Issue Checklist
我使用的是assets下的图片
在页面a和页面b使用同一张图，会导致播放停止，从b页面返回a页面同样看到a页面的apng播放停止。
我猜测是因为使用了同一张资源，于是我尝试使用两种办法加载他，在页面a使用glide：
``` GlideApp.with(this).load(url).into(img)```
在页面b使用APNGDrawable
```
 img.setImageDrawable(APNGDrawable.fromAsset(this,
                    url.substring(url.lastIndexOf('/') + 1, url.length)))
```
仍无法解决此问题，请求大神帮助。

复现方法：
使用同一张assets下图片，页面a可以跳转到页面b。

**Comment by penfeizhou** [comment]
在A,B两个页面都使用Glide加载同一张图片时Glide会复用Drawable,但Android机制决定了Drawable只能设置在一个Image有效,否则Drawable无法正确刷新. 你可以有两种方式解决:
   1.在从页面B返回页面A时重新执行`GlideApp.with(this).load(url).into(img)`,
   2.给Glide设置不可复用的key
```java
GlideApp.with(imageView)
                    .applyDefaultRequestOptions(new RequestOptions().signature(new ObjectKey(UUID.randomUUID())))
                    .load(url)
                    .into(imageView);
```

而针对你所描述的A使用Glide,B使用APNGDrawable,这种情况我认为不应该会有问题.

**Comment by mafanwei** [comment]
使用.applyDefaultRequestOptions确实生效了，但是两种加载方法确实存在上述问题

**Comment by penfeizhou** [comment]
这是glide复用Drawable导致的，close
