### ISSUE TITLE
不能使用 glide 加载apng 或者 webp

### ISSUE THREAD

**Issue by javavaan** [penfeizhou/APNG4Android#83]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | e.g. Huawei Mate 30 pro                               |      |
| System Version               | e.g.  6.0                                             |      |
| APNG4Android Library Version | e.g.  1.0.0                                           |      |
| Repro rate                   | e.g. all the time (100%) / sometimes x% / only once   |      |
| Repro with our demo project  | e.g. does it happen with our demo project?            |      |
| Demo project link            | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by penfeizhou** [comment]
首先,直接使用我们提供的APNGDrawable或者WebPDrawable是否有问题
```java
// Load from asset file
AssetStreamLoader assetLoader = new AssetStreamLoader(context, "wheel.png");


// Load form Resource
ResourceStreamLoader resourceLoader = new ResourceStreamLoader(context, R.drawable.sample);


// Load from file
FileStreamLoader fileLoader = new FileStreamLoader("/sdcard/Pictures/1.webp");


// Create APNG Drawable
APNGDrawable apngDrawable = new APNGDrawable(assetLoader);

//Create Animated webp drawable
WebPDrawable webpDrawable = new WebPDrawable(assetLoader);
```
其次,查看下Glide文档并检查一下项目中的Gradle配置,确认Glide是否正确设置.
如果还有问题,请提供下问题文件或者demo工程.

**Comment by javavaan** [comment]
直接使用APNGDrawable没有问题。

这个是项目中的依赖：

`dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    implementation 'com.github.penfeizhou.android.animation:apng:2.5.1'

    def GLIDE_VERSION = "4.11.0"
    implementation "com.github.bumptech.glide:glide:${GLIDE_VERSION}"
    annotationProcessor "com.github.bumptech.glide:compiler:${GLIDE_VERSION}"
    implementation 'com.github.penfeizhou.android.animation:glide-plugin:2.5.1'

}`

这个是使用方法：

`Glide.with(imageView).load(R.drawable.test).into(imageView)`

R.drawable.test 是一张本地apng图片

**Comment by javavaan** [comment]
> 首先,直接使用我们提供的APNGDrawable或者WebPDrawable是否有问题
> 
> ```java
> // Load from asset file
> AssetStreamLoader assetLoader = new AssetStreamLoader(context, "wheel.png");
> 
> 
> // Load form Resource
> ResourceStreamLoader resourceLoader = new ResourceStreamLoader(context, R.drawable.sample);
> 
> 
> // Load from file
> FileStreamLoader fileLoader = new FileStreamLoader("/sdcard/Pictures/1.webp");
> 
> 
> // Create APNG Drawable
> APNGDrawable apngDrawable = new APNGDrawable(assetLoader);
> 
> //Create Animated webp drawable
> WebPDrawable webpDrawable = new WebPDrawable(assetLoader);
> ```
> 
> 其次,查看下Glide文档并检查一下项目中的Gradle配置,确认Glide是否正确设置.
> 如果还有问题,请提供下问题文件或者demo工程.

麻烦看一下使用方式

**Comment by penfeizhou** [comment]
`Glide.with(imageView).load(R.drawable.test).into(imageView)`
请不要把APNG图片放在Drawable里,放在assets下.APK编译时AAPT工具会压缩PNG资源,破坏APNG的动画格式.

**Comment by javavaan** [comment]
> `Glide.with(imageView).load(R.drawable.test).into(imageView)`
> 请不要把APNG图片放在Drawable里,放在assets下.APK编译时AAPT工具会压缩PNG资源,破坏APNG的动画格式.

把图片放到 drawable 不使用glide，只使用 APNGDrawable 是没问题的。只有配合glide的时候有问题
ResourceStreamLoader resourceLoader = new ResourceStreamLoader(context, R.drawable.sample);
APNGDrawable apngDrawable = new APNGDrawable(assetLoader);

**Comment by penfeizhou** [comment]
Glide不支持加载放在Drawable里的动图,默认只会解析为静图,你直接用ResourceStreamLoader加载好了.
