### ISSUE TITLE
Webps with transparent (alpha) is not rendered correctly

### ISSUE THREAD

**Issue by johnaziz57** [penfeizhou/APNG4Android#86]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | emulator Pixel 2, OnePlus 7                            |      |
| System Version               | API 26, 29                                             |      |
| APNG4Android Library Version | glide-plugin 2.5.1                                           |      |
| Repro rate                   | all the time (100%) |
| Repro with our demo project  | https://github.com/johnaziz57/APNG4Android_Issue  |      |

### Issue Description and Steps

It seems that this glide plugin is not able to render the alpha channel correctly, either that or it doesn't clear the transparent area after it was created the first time

# Used file
Can be found here https://ezgif.com/images/format-demo/butterfly-small.webp

# Correct animation
![correct_animation](https://user-images.githubusercontent.com/14923445/103481137-19248d80-4dd9-11eb-9e06-baf8c8b07bee.gif)

# Current animation
![wrong_animation_2](https://user-images.githubusercontent.com/14923445/103481224-d0210900-4dd9-11eb-8d16-b375da38d835.gif)

**Comment by penfeizhou** [comment]
Hi, Thanks for feedback!!!
We have fixed it at version 2.5.3.

**Comment by johnaziz57** [comment]
@penfeizhou Thanks a lot 🙇

**Comment by johnaziz57** [comment]
@penfeizhou, I added a comment to your changes
hope you can find it helpful
https://github.com/penfeizhou/APNG4Android/commit/f50c974057cd3df9639752dd68bbd8a3edd7f26d#r46374636

**Comment by penfeizhou** [comment]
@johnaziz57 Yes,thanks for reminding.
