### ISSUE TITLE
demo 里的 APNGTestActivity都是静态图

### ISSUE THREAD

**Issue by javavaan** [penfeizhou/APNG4Android#87]
大神你好，我运行你的demo里的APNGTestActivity，显示的都是静态图。
我看这个页面的实现用的是Glide
ImageView imageView = new ImageView(this);
            LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
            layoutParams.bottomMargin = 50;
            layoutParams.topMargin = 50;
            linearLayout.addView(imageView, layoutParams);
            GlideApp.with(imageView)
                    .asBitmap()
                    .apply(RequestOptions.decodeTypeOf(Object.class))
                    .load(url)
                    .set(AnimationDecoderOption.DISABLE_ANIMATION_GIF_DECODER, false)
                    .into(imageView);

请问如果用Glide加载apng，只能显示静态图吗

**Comment by penfeizhou** [comment]
.asBitmap()调用会将动图作为静图加载,你去掉就可以了

**Comment by javavaan** [comment]
去掉之后就什么也不显示了。。。

**Comment by penfeizhou** [comment]
.asBitmap()
.apply(RequestOptions.decodeTypeOf(Object.class))
这两行删掉就行了
