### ISSUE TITLE
使用glide加载apng的方式，一个页面存在两个以上的imageview加载相同的资源url时，只有其中一个是播放正常的

### ISSUE THREAD

**Issue by neil-zhao** [penfeizhou/APNG4Android#88]
如题
使用glide加载apng的方式，一个页面存在两个以上的imageview加载相同的资源url时，只有其中一个是播放正常的，其它的几个都是不动的。
大概看了下源码，发现glide加载的url相同时，实际上是一份缓存数据，同时也只有一个FrameSeqDecoder，但FrameSeqDecoder只能工作在一个imageview下。所以以会出现相同资源的APNG只能播放一个的问题。
希望能够修复这个问题，这种场景还是挺常见的。

**Comment by neil-zhao** [comment]
我通过Glide.with(imageView).load(new CachedImage(imageUrl)).listener(listener).into(imageView);这种方法，将imageUrl包装成一个对象，每次加载时都创建一个新的CachedImage对象可以解决只播放一个的问题，但这种方法根本没有解决问题，因为这样相当于让glide每次load时都创建了一个新的缓存数据(同时也创建了一个新的FrameSeqDecoder)，而且这个缓存数据无法被复用。

**Comment by neil-zhao** [comment]
或者我通过
Glide.with(imageView).load(new CachedImage(imageUrl)).skipMemoryCache(true).listener(listener).into(imageView);这种方法可以解决内存缓存多个无效的APNGDrawable的问题，但同时也无法使用内存缓存了。同样这也不是一个好的解决文案

**Comment by penfeizhou** [comment]
您可以参考这个Issue #40 
由于Android平台的限制,对于动画类的Drawable,同一个实例设置到多个ImageView上,只有最后一个设置的ImageView才有动画效果.所以对于在多个ImageView上展示同一张动画的情况,就不要共用Drawable实例了

**Comment by neil-zhao** [comment]
这样相当于使用skipMemoryCache，取消内存缓存，每次都读文件，这用glide加载apng就失去了意义。本来使用glide就是想使用glide的内存管理apng资源的。

**Comment by penfeizhou** [comment]
这个动画库播放结束会立即回收内存,本来就不在内存中缓存位图数据,所以内存缓存没有意义.

**Comment by neil-zhao** [comment]
这个库是没有内存缓存的逻辑，但通过glide加载apng默认是会缓存这些APNGDrawable的
{@link com.bumptech.glide.load.engine.Engine}
@Nullable
  private EngineResource<?> loadFromMemory(
      EngineKey key, boolean isMemoryCacheable, long startTime) {
    if (!isMemoryCacheable) {
      return null;
    }

    EngineResource<?> active = loadFromActiveResources(key);
    if (active != null) {
      if (VERBOSE_IS_LOGGABLE) {
        logWithTimeAndKey("Loaded resource from active resources", startTime, key);
      }
      return active;
    }

    EngineResource<?> cached = loadFromCache(key);
    if (cached != null) {
      if (VERBOSE_IS_LOGGABLE) {
        logWithTimeAndKey("Loaded resource from cache", startTime, key);
      }
      return cached;
    }

    return null;
  }

@Override
  public void onResourceReleased(Key cacheKey, EngineResource<?> resource) {
    activeResources.deactivate(cacheKey);
    if (resource.isMemoryCacheable()) {
      cache.put(cacheKey, resource);
    } else {
      resourceRecycler.recycle(resource, /*forceNextFrame=*/ false);
    }
  }

现在的库假如使用随机URL的方式，glide的这层内存缓存根本清除不掉，除非FrameDrawableTranscoder->getSize返回真实的大小

**Comment by penfeizhou** [comment]
是的,感谢反馈,这个问题近期会修复下

**Comment by penfeizhou** [comment]
2.6.0版本修复两个问题
1. 使用Glide时可能导致的内存泄漏
2. 动画Drawable设置到多个ImageView时,只有一个播放正常.

**Comment by cat9** [comment]
用了这个库之后，上报的OutOfMemoryError多了很多

**Comment by bad-mask** [comment]
Glide.with(context).load(url).into(imageview)
