### ISSUE TITLE
glide加载apng内存泄露问题

### ISSUE THREAD

**Issue by neil-zhao** [penfeizhou/APNG4Android#89]
继续上一个问题  [https://github.com/penfeizhou/APNG4Android/issues/88](url)
这个库是没有内存缓存的逻辑，但通过glide加载apng默认是会缓存这些APNGDrawable的
{@link com.bumptech.glide.load.engine.Engine}
@nullable
private EngineResource<?> loadFromMemory(
EngineKey key, boolean isMemoryCacheable, long startTime) {
if (!isMemoryCacheable) {
return null;
}

EngineResource<?> active = loadFromActiveResources(key);
if (active != null) {
  if (VERBOSE_IS_LOGGABLE) {
    logWithTimeAndKey("Loaded resource from active resources", startTime, key);
  }
  return active;
}

EngineResource<?> cached = loadFromCache(key);
if (cached != null) {
  if (VERBOSE_IS_LOGGABLE) {
    logWithTimeAndKey("Loaded resource from cache", startTime, key);
  }
  return cached;
}

return null;
}

@override
public void onResourceReleased(Key cacheKey, EngineResource<?> resource) {
activeResources.deactivate(cacheKey);
if (resource.isMemoryCacheable()) {
cache.put(cacheKey, resource);
} else {
resourceRecycler.recycle(resource, /forceNextFrame=/ false);
}
}

现在的库针对相同资源URL随机拼接字符的方式，glide的这层内存缓存会一直涨，除非FrameDrawableTranscoder->getSize返回真实的大小。而且glide缓存的随机url后，无法复用缓存。

**Comment by penfeizhou** [comment]
Duplicate of #88
