### ISSUE TITLE
How can I use it as full size?

### ISSUE THREAD

**Issue by chanjungkim** [penfeizhou/APNG4Android#9]
I am using this library. And it is very cool compared to others...

However, the ratio seems fixed. is there any way to change it into match_parent/match_parent?

**Comment by penfeizhou** [comment]
Hi there, the scale size or ratio can be changed.The drawable's size is depending on the image view's size and scale type which be set on.
So if you need the drawable to be match parent, you can just let your image view match parent.The animation drawable onto it will be drawed as match parent.

**Comment by chanjungkim** [comment]
How can I change the ratio? I mean when I do match_parent, the ratio is kept and it has empty spaces at the sides. I want it to fill the whole screen.

**Comment by chanjungkim** [comment]
Is there any solution???

**Comment by penfeizhou** [comment]
Layout xml like this，and set apngdrawable to imageview by java code.
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/imageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:scaleType="centerInside"
        android:src="@drawable/ic_launcher_background" />

</LinearLayout>`

If this still cannot solve your problem,please provide me more information,best is demo code

**Comment by penfeizhou** [comment]
You can change the android:scaleType to archive your requirement

**Comment by chanjungkim** [comment]
`centerInside` is not the right one. It makes my apng smaller and stay in the center.

I guess the closest one that I want to implement is `centerCrop` or `fitCenter`. However, `centerCrop` can cut off some part of the apng. And `fitCenter` doesn't loose any part, however, it keeps the ratio and have empty spaces at "the sides" or "the bottom and the top" depending on the ratio.

**Comment by penfeizhou** [comment]
So your real problem is that your image or animation's size not match your phone screen.It's your choice to decide how to deal with it.Either you can display part of the image,or you can only clip the image to fit the screen.
