### ISSUE TITLE
自动循环播放场景,我复用了APNGDrawable,复用的会停留在最后一帧在重新播放,导致了闪现现象

### ISSUE THREAD

**Issue by nicelyjust** [penfeizhou/APNG4Android#90]
你好,复用代码如下

`
private APNGDrawable getApngDrawable(int index) {
        APNGDrawable apngDrawable = mDrawableHashMap.get(index);
        if (apngDrawable == null) {
            apngDrawable = new APNGDrawable(new AssetStreamLoader(this, assertList[index]));
            mDrawableHashMap.put(index, apngDrawable);
            mAPNGDrawables.add(index, apngDrawable);
            return apngDrawable;
        }
        apngDrawable.reset();
        apngDrawable.clearAnimationCallbacks();
        return apngDrawable;
    }
`

请问有什么办法可以把APNGDrawable 停留在第一帧吗?

**Comment by penfeizhou** [comment]
APNGDrawable默认是自动播放与停止的,不能停留在第一帧.
目前reset API实现中没有清除当前的位图,所以在reset后重新播放可能会有一些闪现的问题.
我这边更新下版本,在reset中清除当前位图.

**Comment by penfeizhou** [comment]
Version:2.7.0

**Comment by nicelyjust** [comment]
@penfeizhou 非常感谢!!!
