### ISSUE TITLE
LockSupport.park 导致 ANR

### ISSUE THREAD

**Issue by yishengma** [penfeizhou/APNG4Android#93]
public Rect getBounds() {
        if (fullRect != null) {
            return fullRect;
        } else {
            if (mState == State.FINISHING) {
                Log.e(TAG, "In finishing,do not interrupt");
            }
            final Thread thread = Thread.currentThread();
            workerHandler.post(new Runnable() {
                @Override
                public void run() {
                    try {
                        if (fullRect == null) {
                            if (mReader == null) {
                                mReader = getReader(mLoader.obtain());
                            } else {
                                mReader.reset();
                            }
                            initCanvasBounds(read(mReader));
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        fullRect = RECT_EMPTY;
                    } finally {
                        LockSupport.unpark(thread);
                    }
                }
            });
            LockSupport.park(thread);
            return fullRect;
        }
    }
    
    //LockSupport.park(thread); 主线程会ANR
    sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
com.github.penfeizhou.animation.decode.FrameSeqDecoder.getBounds(FrameSeqDecoder.java:196)
com.github.penfeizhou.animation.FrameAnimationDrawable.getIntrinsicWidth(FrameAnimationDrawable.java:197)
android.widget.ImageView.invalidateDrawable(ImageView.java:284)
android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:477)
android.graphics.drawable.Drawable.setVisible(Drawable.java:928)
com.github.penfeizhou.animation.FrameAnimationDrawable.setVisible(FrameAnimationDrawable.java:191)
android.widget.ImageView.updateDrawable(ImageView.java:1062)
android.widget.ImageView.setImageDrawable(ImageView.java:592)

**Comment by jingpeng** [comment]
麻烦提供下设备和具体图片理论上workhandler不是主线程，有可能设备handlerthread初始化过慢或失败
