### ISSUE TITLE
java.lang.NullPointerException  Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference

### ISSUE THREAD

**Issue by HymanYang** [penfeizhou/APNG4Android#94]
FrameAnimationDrawable，有4%的概率报空指针，需要严谨下逻辑

com.github.penfeizhou.animation.FrameAnimationDrawable.int getMemorySize()(FrameAnimationDrawable.java:276)
--
2 com.github.penfeizhou.animation.glide.FrameDrawableTranscoder$3.int getSize()(FrameDrawableTranscoder.java:93)
3 com.bumptech.glide.load.engine.EngineResource.int getSize()(EngineResource.java:62)
4 com.bumptech.glide.load.engine.cache.LruResourceCache.int getSize(com.bumptech.glide.load.engine.Resource)(LruResourceCache.java:40)
5 com.bumptech.glide.load.engine.cache.LruResourceCache.int getSize(java.lang.Object)(LruResourceCache.java:11)
6 com.bumptech.glide.util.LruCache.java.lang.Object put(java.lang.Object,java.lang.Object)(LruCache.java:131)
7 com.bumptech.glide.load.engine.cache.LruResourceCache.com.bumptech.glide.load.engine.Resource put(com.bumptech.glide.load.Key,com.bumptech.glide.load.engine.Resource)(LruResourceCache.java:11)
8 com.bumptech.glide.load.engine.Engine.void onResourceReleased(com.bumptech.glide.load.Key,com.bumptech.glide.load.engine.EngineResource)(Engine.java:397)
9 com.bumptech.glide.load.engine.EngineResource.void release()(EngineResource.java:116)
10 com.bumptech.glide.load.engine.EngineJob.void decrementPendingCallbacks()(EngineJob.java:293)
11 com.bumptech.glide.load.engine.EngineJob$CallResourceReady.void run()(EngineJob.java:431)
12 android.os.Handler.handleCallback(Handler.java:900)
13 android.os.Handler.dispatchMessage(Handler.java:103)
14 android.os.Looper.loop(Looper.java:219)
15 android.app.ActivityThread.main(ActivityThread.java:8387)
16 java.lang.reflect.Method.invoke(Native Method)
17 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by penfeizhou** [comment]
这里确实有问题,版本`v2.7.0`带入的错误逻辑.
请升级到v2.8.0版本,修复了此问题.
感谢反馈.
