### ISSUE TITLE
WebPEncoder overlays all Frames

### ISSUE THREAD

**Issue by AaronMaria** [penfeizhou/APNG4Android#95]
It works in creating the animated WebP, but each Frame seems to include all previous Frames.
Can you tell me if I did something wrong, here is a snippet:

      drawable = ApngDrawable.decode(getInputStream(uri))
      val encoder = WebPEncoder()
      for (frameNum in 0 until drawable.frameCount) {
          drawable.seekToFrame(0, frameNum)
          var frame = scaleToAlternative(drawableToBitmap(drawable.current)!!, 512, 512, 16)
          encoder.addFrame(frame, 0, 0, drawable.frameDurations[frameNum])
      }
      createFile(encoder.build(), path)

I try to create an animated WebP from an APNG.

**Comment by AaronMaria** [comment]
I got it, disposal seems to be on by default

**Comment by penfeizhou** [comment]
Yes,it's a simple translation.
If you need more adavanced usage for better performance or compression,please see https://developers.google.com/speed/webp/download.

**Comment by CrackerKSR** [comment]
Can you show snippet for decoding animated webp and get each frames as bitmap

**Comment by CrackerKSR** [comment]
> I got it, disposal seems to be off by default

How did you enable it?
