### ISSUE TITLE
2.8.0 Failed to resolve: glide-plugin

### ISSUE THREAD

**Issue by chenyunecjtu** [penfeizhou/APNG4Android#96]

**Comment by penfeizhou** [comment]
It's been published to jcenter ,please retry.
You can see by this url : 
https://jcenter.bintray.com/com/github/penfeizhou/android/animation/glide-plugin/2.8.0/

**Comment by chenyunecjtu** [comment]
can support jitpact

**Comment by penfeizhou** [comment]
You only need to make sure below codes in your project's gradle
```groovy
allprojects {
    repositories {
       ...
        jcenter()
    }
}
```

**Comment by chenyunecjtu** [comment]
allprojects {
    repositories {
        maven { url 'https://www.jitpack.io' }
        //加入下面这句
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
 
        google()
        jcenter()
     
        maven { url "https://maven.google.com" }
    }
}
