### ISSUE TITLE
2.6.0及以后增加的getMemorySize方法返回的值不一致，导致泄露问题

### ISSUE THREAD

**Issue by neil-zhao** [penfeizhou/APNG4Android#98]
通过黄点调试com.bumptech.glide.util.LruCache类发现同一个资源的put时currentSize增加的getSize和remove时getSize获取的大小不一致，导致currentSize持续增长，直到触发trimToSize方法发生NoSuchElementException异常

zdt apngSize:506 hashCode:18168044
zdt put currentSize:1706 getSize:506 old is null:true
zdt apngSize:300 hashCode:48391513
zdt remove currentSize:1406 true
zdt apngSize:1200 hashCode:48391513
zdt put currentSize:2606 getSize:1200 old is null:true
zdt apngSize:126 hashCode:18168044
zdt remove currentSize:2479 true
zdt apngSize:506 hashCode:18168044
zdt put currentSize:2985 getSize:506 old is null:true
zdt apngSize:300 hashCode:48391513
zdt remove currentSize:2685 true
zdt apngSize:1200 hashCode:48391513
zdt put currentSize:3885 getSize:1200 old is null:true
zdt apngSize:126 hashCode:18168044
zdt remove currentSize:3759 true
zdt apngSize:506 hashCode:18168044
zdt put currentSize:4265 getSize:506 old is null:true
zdt apngSize:300 hashCode:48391513
zdt remove currentSize:3965 true
zdt apngSize:1200 hashCode:48391513
zdt put currentSize:5165 getSize:1200 old is null:true
zdt apngSize:126 hashCode:18168044
zdt remove currentSize:5039 true
zdt apngSize:506 hashCode:18168044
zdt put currentSize:5545 getSize:506 old is null:true
zdt apngSize:300 hashCode:48391513
zdt remove currentSize:5245 true
zdt apngSize:1200 hashCode:48391513
zdt put currentSize:6445 getSize:1200 old is null:true
zdt apngSize:126 hashCode:18168044
zdt remove currentSize:6318 true

hashCode为18168044、48391513的两张图，交替轮播。从log中可以看出48391513的size一直是300、1200切换，而且是put的时候1200,remove的时候300。

测试代码
String[] urls = new String[]{"https://misc.aotu.io/ONE-SUNDAY/apng_spinfox.png",
            "https://misc.aotu.io/ONE-SUNDAY/SteamEngine.png"
    };
    private int index;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_apnglib);
        txtClear = findViewById(R.id.txtClear);
        apng_image1 = findViewById(R.id.apng_image1);

        txtClear.postDelayed(runnable, 2000 * 1);
    }

    private Runnable runnable = new Runnable() {

        @Override
        public void run() {
            updateImageView(apng_image1);
            txtClear.postDelayed(runnable, 2000 * 1);
        }
    };

    private String getImageUrl() {
        index++;
        return urls[index % urls.length];
    }

    private void updateImageView(ImageView apng_image) {
        String imageUrl = getImageUrl();
        Glide.with(APNGTestActivity.this).load(imageUrl).into(apng_image);
        Log.d(TAG, "updateImageView imageUrl:" + imageUrl);
    }

**Comment by jingpeng** [comment]
我测试了下currentSize并未持续增长，
![Uploading 截屏2021-03-04 上午10.21.42.png…]()
![Uploading 截屏2021-03-04 上午10.21.56.png…]()

**Comment by jingpeng** [comment]
我测试验了下并无持续增长

**Comment by jingpeng** [comment]
<img width="997" alt="Current Size 3509020" src="https://user-images.githubusercontent.com/5223226/109901239-af8b0780-7cd3-11eb-9bcf-64f4adf5bf46.png">

**Comment by jingpeng** [comment]
<img width="995" alt="Current Size 3289436" src="https://user-images.githubusercontent.com/5223226/109901316-cfbac680-7cd3-11eb-94a2-e3ae2f744d44.png">

**Comment by jingpeng** [comment]
Current Size始终在这两个数值内进行变更，因此目前并未出现所谓的持续增长

**Comment by neil-zhao** [comment]
确实是有问题的，可以在getMemorySize方法处打个LOG，确认是否存在同一资源返回的大小不一致即可，cacheBitmap存放的bitmap资源开始播放时拿到的大小，和更换下一资源innerStop后是不一样的。

**Comment by jingpeng** [comment]
我只看到两个数值
2021-03-04 10:47:44.638 15139-15139/com.github.penfeizhou.animation.demo E/MemorySize: 87620
2021-03-04 10:48:06.825 15139-15139/com.github.penfeizhou.animation.demo E/MemorySize: 307204

**Comment by kingideayou** [comment]
这个是 Glide 实现的 LRUCache 的问题？https://github.com/bumptech/glide/issues/4391

**Comment by jingpeng** [comment]
如果你把间隔调到很短，每个资源的渲染还没完成，整个framebuffer和bitmap的size还没完全算好，确实会有size不同

**Comment by jingpeng** [comment]
> 如果你把间隔调到很短，每个资源的渲染还没完成，整个framebuffer和bitmap的size还没完全算好，确实会有size不同

比如说100ms

**Comment by jingpeng** [comment]
增加了一个commit，规避了一处Crash：
https://github.com/penfeizhou/APNG4Android/commit/15169497260d7f8d6a7dcb41d2f5becc8847e031

**Comment by jingpeng** [comment]
另外目前glide 4.11的问题，需要你使用时更新到glide 4.12 @neil-zhao

**Comment by kingideayou** [comment]
> 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)

或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547

**Comment by jingpeng** [comment]
> > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> 
> 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547

这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好

**Comment by kingideayou** [comment]
> > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > 
> > 
> > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> 
> 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好

Glide 4.12 也不能保持这个库计算的 size 一致吧？

**Comment by jingpeng** [comment]
> > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > 
> > > 
> > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > 
> > 
> > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> 
> Glide 4.12 也不能保持这个库计算的 size 一致吧？

4.12我测了是不会崩溃的

**Comment by kingideayou** [comment]
> > > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > > 
> > > > 
> > > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > > 
> > > 
> > > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> > 
> > 
> > Glide 4.12 也不能保持这个库计算的 size 一致吧？
> 
> 4.12我测了是不会崩溃的

我还没跑代码
我看他这个 Entry 类本质上也是一个缓存，里面的 size 是什么时候设置的？可能也不是最终的 size

**Comment by jingpeng** [comment]
> > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > 
> > > 
> > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > 
> > 
> > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> 
> Glide 4.12 也不能保持这个库计算的 size 一致吧？
> 
> > > > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > > > 
> > > > > 
> > > > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > > > 
> > > > 
> > > > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> > > 
> > > 
> > > Glide 4.12 也不能保持这个库计算的 size 一致吧？
> > 
> > 
> > 4.12我测了是不会崩溃的
> 
> 我还没跑代码
> 我看他这个 Entry 类本质上也是一个缓存，里面的 size 是什么时候设置的？可能也不是最终的 size

Glide 4.12修复了这个size变化的问题，认为size变化就算evicted

**Comment by kingideayou** [comment]
> > > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > > 
> > > > 
> > > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > > 
> > > 
> > > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> > 
> > 
> > Glide 4.12 也不能保持这个库计算的 size 一致吧？
> > > > > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > > > > 
> > > > > > 
> > > > > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > > > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > > > > 
> > > > > 
> > > > > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> > > > 
> > > > 
> > > > Glide 4.12 也不能保持这个库计算的 size 一致吧？
> > > 
> > > 
> > > 4.12我测了是不会崩溃的
> > 
> > 
> > 我还没跑代码
> > 我看他这个 Entry 类本质上也是一个缓存，里面的 size 是什么时候设置的？可能也不是最终的 size
> 
> Glide 4.12修复了这个size变化的问题，认为size变化就算evicted

看了下 4.12 代码，原理就是缓存了第一次获取的 size，保证 currentSize 大小是正确的，避免了`cacheIterator.next()` 崩溃，本质上和给 `getMemorySize()` 加缓存是一致的，不过他可能更通用些。

**Comment by kingideayou** [comment]
> > > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > > 
> > > > 
> > > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > > 
> > > 
> > > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> > 
> > 
> > Glide 4.12 也不能保持这个库计算的 size 一致吧？
> > > > > > > 这个是 Glide 实现的 LRUCache 的问题？[bumptech/glide#4391](https://github.com/bumptech/glide/issues/4391)
> > > > > > 
> > > > > > 
> > > > > > 或者给 getSize() 方法加个缓存？保证前后获取到 size 是一致的？
> > > > > > https://github.com/penfeizhou/APNG4Android/blob/8f7fe76269df5566e9028ea29b6d6e251f7c0a3e/frameanimation/src/main/java/com/github/penfeizhou/animation/decode/FrameSeqDecoder.java#L547
> > > > > 
> > > > > 
> > > > > 这个不行，因为还没渲染出来后续部分动画的时候，你的大小肯定是不确定的，还是用glide 4.12解决最好
> > > > 
> > > > 
> > > > Glide 4.12 也不能保持这个库计算的 size 一致吧？
> > > 
> > > 
> > > 4.12我测了是不会崩溃的
> > 
> > 
> > 我还没跑代码
> > 我看他这个 Entry 类本质上也是一个缓存，里面的 size 是什么时候设置的？可能也不是最终的 size
> 
> Glide 4.12修复了这个size变化的问题，认为size变化就算evicted

看了下 4.12 代码，原理就是缓存了第一次获取的 size，保证 currentSize 大小是正确的，避免了`cacheIterator.next()` 崩溃，本质上和给 `getMemorySize()` 加缓存是一致的，不过他可能更通用些。
