### ISSUE TITLE
APNGDrawable.stop() not stopping animation with ImageButton

### ISSUE THREAD

**Issue by FredHappyface** [penfeizhou/APNG4Android#99]
- [x] I have searched for a similar issue in the [project](https://github.com/penfeizhou/APNG4Android/issues) and found none

### Issue Info

| Info                         | Value                                                 |      |
| ---------------------------- | ----------------------------------------------------- | ---- |
| Device Info                  | Nokia 8 Sirocco                               |      |
| System Version               | 10                                             |      |
| APNG4Android Library Version | 2.10.0                                      |      |
| Repro rate                   | All the time (100%)   |      |
| Repro with our demo project  | Unsure            |      |
| Demo project link            | Code snipper below  |      |

### Code snippet 

```java
private void setStickerButtonImage(File sticker, ImageButton btn) {
    String sName = sticker.getName();
    ImageDecoder.Source source = ImageDecoder.createSource(sticker);
    Drawable drawable = null;
    try {
        drawable = ImageDecoder.decodeDrawable(source);
    } catch (IOException e) {
        e.printStackTrace();
    }
    if (sName.contains(".png")||sName.contains(".apng")){
        drawable = APNGDrawable.fromFile(sticker.getAbsolutePath());
    }
    if (drawable instanceof APNGDrawable && sharedPref.getBoolean("disable_animations", false) ) {
        ((APNGDrawable) drawable).stop();
    }
    btn.setImageDrawable(drawable);
    if (drawable instanceof AnimatedImageDrawable && !sharedPref.getBoolean("disable_animations", false) ) {
        ((AnimatedImageDrawable) drawable).start();
    }

}
```

### Minimal Example

```java
private void setStickerButtonImage(File sticker, ImageButton btn) {
    Drawable  drawable = APNGDrawable.fromFile(sticker.getAbsolutePath());
    ((APNGDrawable) drawable).stop();
    btn.setImageDrawable(drawable);
}
```

### Issue Description and Steps

((APNGDrawable) drawable).stop(); does not stop the animation when applies to a ImageButton

Looking at https://github.com/penfeizhou/APNG4Android/blob/master/frameanimation/src/main/java/com/github/penfeizhou/animation/FrameAnimationDrawable.java
I would have expected this to stop any animation but this doesn't appear to be the case in testing

Thank you for your time

**Comment by penfeizhou** [comment]
The Animation's start and stop is called automatically.If you need control manually ，please call animation.setAutoPlay(false) first.
Then you can call start or stop as you need.

**Comment by penfeizhou** [comment]
Closing
